suitenumerique/people

.github/workflows/people.yml
.github/workflows/secrets.enc.env
.sops.yaml
scripts/install-pre-commit-hook.sh

Github secrets are difficult to maintain in time because we do not have a way to track them efficiently. So to avoid this issue, we prefer to use sops encrypted files to manage our secrets.

👷(ci) Configure workflows to use sops secrets instead of github secrets

---

renovate.json

Use the right Python match manager when ignoring dependencies.
The current Renovate configuration is using the wrong match manager, as our project utilizes `pyproject.toml` instead of `setup.cfg`. This commit corrects the configuration to ensure compatibility with our project structure.

🔧(project) update Renovate configuration to fix match manager issue

---

src/backend/core/api/viewsets.py
src/backend/core/tests/test_api_users.py

A previous PR enabled user search using the email. After discussing models, we chose to enable research on emails provided on identities, and return linked user.
Description...

🐛(api) enable search on identities

---

.github/workflows/docker-hub.yml
.github/workflows/people.yml
.github/workflows/secrets.enc.env

Publish production Docker images for staging deployment.
I have followed [the basic usage of these configurations](https://github.com/docker/build-push-action).
Images are pushed to this [public Docker Hub repository](https://hub.docker.com/repository/docker/lasuite/people/general).
It closes, #39 .

Update CI to publish docker image

---

src/backend/core/admin.py
src/backend/core/models.py

Make Team's Slug field non-editable in the Django admin.
Avoids UX issues by preventing accidental slug overwrites during updates. The Slug is now conveniently displayed in the teams list view.
Before:
https://github.com/numerique-gouv/people/assets/45729124/d95ebdfb-b898-47bf-951d-63f239e3c9b7
After:
https://github.com/numerique-gouv/people/assets/45729124/b4299471-184e-41ce-86a8-b84f6016382c

🩹(backend) enhance Django Admin for Team Slug

---

src/backend/core/admin.py
src/backend/core/models.py

Fix several issues identified in the Django Admin
**Broken Identity string representation**
Resolving a format error in the Identity string representation caused by potential `None` values in the email field. This issue was discovered when attempting to access the User details page in the Django Admin
**Broken User creation form**
The replacement of the User's username with an email led to errors in the `UserAdmin` class. The base class used the `username` field in the `add_fieldsets` attribute. This problem was discovered while attempting to create a new user in the Django Admin.
It closes #56.

🩹(backend) fix Django Admin UserAdmin page

---

docker-compose.yml
docker/files/etc/nginx/conf.d/default.conf
src/backend/people/settings.py

Fix Nginx commented broken configuration.
Issue identified on Joanie. The production image, running with docker-compose, uses a Django environment which requires some dev dependencies. Dev dependencies are not installed in the production image.
Create a new Django environment, dedicated to test locally the production image. As the production image was crashing, the Nginx configuration was also broken.
Linked to this issue, our container lacked monitoring container readiness. I have activated container liveness probes, which will be useful in the near future with K8s.

🐛(project) run production image locally with docker-compose

---

src/frontend/apps/desk/src/features/teams/api/types.tsx
src/frontend/apps/desk/src/features/teams/api/useCreateTeam.tsx
src/frontend/apps/desk/src/features/teams/api/useTeam.tsx
src/frontend/apps/desk/src/features/teams/api/useTeams.tsx
src/frontend/apps/desk/src/features/teams/components/PanelTeam.tsx
src/frontend/apps/desk/src/features/teams/components/PanelTeams.tsx
src/frontend/apps/desk/src/pages/AppProvider.tsx
src/frontend/apps/desk/src/pages/teams/[id].tsx
src/frontend/apps/desk/src/pages/teams/create.tsx
src/frontend/apps/e2e/__tests__/app-desk/teams-create.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/teams-panel.spec.ts

Integrate dynamic route `teams/[id]`.

✨(frontend) The base of page team

---

src/frontend/apps/desk/src/pages/index.tsx
src/frontend/apps/desk/src/pages/teams/index.tsx
src/frontend/apps/e2e/__tests__/app-desk/teams-create.spec.ts

We have this kind of url `/teams/1321465`, but `/teams/` gives a 404, it is not a good practice.
We make `/teams` as an alias of the homepage `/`.
[scrnli_2_13_2024_12-03-10 PM.webm](https://github.com/numerique-gouv/people/assets/25994652/6d637779-9574-47ee-83d8-90528303677f)

🎨(frontend) Consistency url

---

.github/workflows/people.yml
env.d/development/common.e2e.dist
src/backend/people/settings.py
src/frontend/apps/desk/src/api/APIError.ts
src/frontend/apps/desk/src/api/index.ts
src/frontend/apps/desk/src/api/utils.ts
src/frontend/apps/desk/src/components/Text.tsx
src/frontend/apps/desk/src/components/TextErrors.tsx
src/frontend/apps/desk/src/features/teams/api/useCreateTeam.tsx
src/frontend/apps/desk/src/features/teams/api/useTeam.tsx
src/frontend/apps/desk/src/features/teams/api/useTeams.tsx
src/frontend/apps/desk/src/i18n/translations.json
src/frontend/apps/desk/src/pages/404.tsx
src/frontend/apps/desk/src/pages/teams/[id].tsx
src/frontend/apps/desk/src/pages/teams/create.tsx
src/frontend/apps/e2e/__tests__/app-desk/teams-create.spec.ts

- Create a 404 page and manage the 404 when we try to access a team that doesn't exist (`/teams/idontexist`).
- We improve the way to catch the api errors, to get an easy way to display dynamically api errors.

🥅(frontend ) page 404

---

src/backend/core/factories.py

Avoid unnecessary nesting when code can early return.
Also, rename "item" to a more explicit name "user_entry".
Yesss this is very-very nit-picking 🥵

🎨(backend) early return in User factory

---

src/backend/core/api/viewsets.py
src/backend/core/tests/team_accesses/test_api_team_accesses_list.py

Abilities on team's accesses were wrongly computed.
This bug was highlighted by @AntoLC, it closes #87

Fix team's accesses abilities

---

src/frontend/apps/desk/src/features/teams/__tests__/MemberGrid.test.tsx
src/frontend/apps/desk/src/features/teams/components/Member/MemberGrid.tsx
src/frontend/apps/e2e/__tests__/app-desk/team.spec.ts

The roles in the member grid were not being translated. This PR adds the translation for
the roles in the member grid.

🌐(app-desk) translate role in member grid

---

src/frontend/apps/desk/src/features/teams/components/TeamInfo.tsx

Enhance Team info layout
Few minor layout issues were fixed.
First display label and dates inline, so they wrap nicely when screen's size decreases. It also fixes the text overflow when the screen's size is tiny.
Then, align screen with the Figma design, where items are justified on the left of the Team info component.
It closes #84 
https://github.com/numerique-gouv/people/assets/45729124/3c745a97-9221-484b-8b3d-0e9e5e761ccf

🩹(frontend) fix layout overflow in Team info

---

src/backend/core/api/viewsets.py
src/backend/core/tests/test_api_users.py

We introduce user's name, we should be able to search user both on their email and name
Inspired by `Contact` search feature, refactor the current search logic on the user, to include a trigram similarity score on her name, summed up with the existing one, on her email.
Tests might be improved, wdyt @sampaccoud?

Enhance user search

---

src/frontend/apps/desk/src/components/DropButton.tsx

When we were clicking outside the dropdown, the dropdown was not closing.
This PR fixes that.
See: #110
[scrnli_3_13_2024_4-09-54 PM.webm](https://github.com/numerique-gouv/people/assets/25994652/cb1a4467-de9d-45da-b78d-63830aead64b)

🐛(app-desk) close dropDown when click outside

---

src/backend/demo/defaults.py
src/backend/demo/management/commands/create_demo.py

The current implementation of our product demo via the make command lacks user identity for a significant portion of generated users, limiting the realism of the showcased scenarios. As it stands, users created by the make command lack complete information, such as full names and email addresses, because they don't have any identity.
I tried to come up with the simplest solution: we now generate a very small portion of our users with 0 identities. The probability for users to have only 1 identity is the highest but they can have up to 4 with decreasing probabilities. I removed the possibility to set a maximum number of identities as it doesn't bring any value.
3% of the identities created will have no email and 3% will have no name.
Fixes https://github.com/numerique-gouv/people/issues/90

🧑‍💻(demo) improve distribution in number of identities per user

---

Dockerfile

Prepare deployment
`backend-development` and `backend-production` CMD syntaxes were using a Shell Form. Shell form prevented Unix signals from reaching our container correctly, such as SIGTERM. Also, the shell process ends up being the PID 1, instead of our Python scripts.
Docker recommends using the exec form whenever possible.

🐛(docker) switch CMD form from Shell to Exec

---

src/backend/core/models.py
src/backend/core/tests/test_models_invitations.py
src/backend/pyproject.toml

Convert invitations to accesses upon creating a new identity.
I don't remember why but I had noted down that we could add the logic of this PR in `create_user` ([here](https://github.com/numerique-gouv/people/blob/29d274ab7c94768f30752319cabbcc1aee7db142/src/backend/core/authentication.py#L108))
I think it's better to link it to the Identity model because identities and invitations both revolve around the same emails. We could imagine by instance that, later on, upon linking identities to my existing user, I get all the extra accesses linked to my new email/identity.

✨(backend) convert invitations to accesses

---

src/helm/env.d/dev/values.desk.yaml.gotmpl
src/helm/env.d/staging/values.desk.yaml.gotmpl

Admin ingress has been partially renamed to `ingressAdmin`. I forgot to update Helmfile values. Fixed them.

🐛(helm) fix wrongly named ingress

---

src/backend/core/api/viewsets.py
src/backend/core/factories.py
src/backend/core/tests/team_accesses/test_api_team_accesses_list.py
src/backend/core/tests/test_api_users.py
src/backend/core/tests/test_models_users.py

Offer the necessary ordering field to enhance UX when manipulating Team's data in the member grid.
Add API ordering fields on the TeamAccess endpoint. Please note that, frontend is almost ready, and being blocked by issue on Cunnigham side. One was merged, another is still being discussed. 
I prefer shipping the backend first, and opening a new PR for the frontend when all elements will be available.
This PR is related to #81

✨(api) support ordering when listing team's accesses

---

.github/workflows/people.yml

The CI was controlling if the traduction was made in every PR. It makes the workflow quite grueling when we have to change the literal, plus the synch is complicating when we have multiple PR opened.
We remove the CI control on the traduction, we will do dedicated PR to update the traduction.
We will add the CI control on the traduction in the future, before a release by example.

🧑‍💻(frontend) remove CI control on traduction frontend

---

renovate.json

Discussed with @sampaccoud, Renovate PR do not necessitate ChangeLog updates Our CI system requires a 'noChangeLog' label or an updated ChangeLog. Currently, we manually add the label for each Renovate PR.
To improve DX, we'll configure Renovate to apply the label automatically.

🔧(renovate) open Renovate PR with a default noChangeLog label

---

src/helm/env.d/staging/values.desk.yaml.gotmpl

Recent changes on the staging cluster created a regression. The ingress `className` needs to be specified.

🚑️(staging) fix 404 errors

---

src/frontend/apps/desk/src/features/members/__tests__/MemberGrid.test.tsx
src/frontend/apps/desk/src/features/members/api/useTeamsAccesses.tsx
src/frontend/apps/desk/src/features/members/components/MemberGrid.tsx

Enhance UX while using the member grid.
Enable sorting on columns. 
Few issues were (or will be) opened on Cunningham. Sorting on Role [was shipped](https://github.com/openfun/cunningham/issues/298), we are waiting for their next release.
https://github.com/numerique-gouv/people/assets/45729124/5d0dbcdb-ba4b-48f1-b11a-e875d558c673

Enable sorting on columns

---

src/frontend/apps/desk/src/features/header/ApplicationsMenu.tsx
src/frontend/apps/desk/src/features/header/Header.tsx
src/frontend/apps/e2e/__tests__/app-desk/header.spec.ts

Based on works from @manuhabitela, introduce a PoC of the future component. `ApplicationsMenu` component is still under construction.
This code was committed for the Wednesday 26th demo, to showcase our future works. This Next.js integration could be improved, and will for sure! Don't blame me.

🚧(frontend) add applications menu PoC

---

src/frontend/apps/desk/src/features/header/ApplicationsMenu.tsx
src/frontend/apps/desk/src/pages/_document.tsx

Importing the css from Head was causing a flickering effect on the button, because of the time the css
load. Next.js was emitting as well a warning about css being loaded from the Head component.
We moved the css import to the _document.tsx file as recommended by the Next.js documentation.
[scrnli_3_29_2024_11-46-32 AM.webm](https://github.com/numerique-gouv/people/assets/25994652/821d44ba-22aa-4479-9b14-595ab6fceee1)

🚨(app-desk) remove warning next.js about css from Head

---

.github/workflows/people.yml
src/frontend/apps/e2e/__tests__/app-desk/member-delete.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/teams-delete.spec.ts
src/frontend/apps/e2e/playwright.config.ts

To improve the speed of the CI, we cache the frontend install. 
**It will even be reused between pull request until the yarn.lock has a change.**
We cache as well the desk build app, in another cache, this cache persist only per workflow. 
It will increase the speed if we have e2e flaky tests and that we have to relaunch the e2e job.
⚠️ Firefox e2e tests are often flaky, Firefox is about 3% of the browser used on the web, we remove the e2e support for the moment: https://gs.statcounter.com/browser-market-share
**From 1m54s to 10 seconds.**

⚡️(CI) persist the frontend between jobs

---

src/frontend/apps/desk/src/features/addMembers/api/useUsers.tsx
src/frontend/apps/desk/src/features/addMembers/components/ModalAddMembers.tsx
src/frontend/apps/desk/src/features/addMembers/components/SearchMembers.tsx
src/frontend/apps/e2e/__tests__/app-desk/member-create.spec.ts

Cannot select user or email already selected.
Lot of flakiness was appearing, we remove the tests e2e with Firefox.

🚸(app-desk) cannot select user or email already selected

---

.github/workflows/people.yml

Node.js 16 actions are deprecated, update them.

Update Github Actions version (Node.js 16 is deprecated)

---

src/backend/core/tests/team_accesses/test_api_team_accesses_list.py

Previously, there was a difference between Django's `order_by` behavior and Python's `sorted` function, leading to test failures under specific conditions. For example, entries such as 'Jose Smith' and 'Joseph Walker' were not consistently sorted in the same order between the two methods.
To resolve this issue, we've ensured that sorting the expected results in the TeamAccess tests are both case-insensitive and space-insensitive. This adjustment fix tests flakiness

🩹(backend) address test flakiness while sorting Team accesses

---

src/frontend/apps/desk/.env.development
src/frontend/apps/desk/.env.production
src/frontend/apps/desk/.env.test
src/frontend/apps/desk/src/api/__tests__/fetchApi.test.tsx
src/frontend/apps/desk/src/api/conf.ts
src/frontend/apps/desk/src/api/fetchApi.ts
src/frontend/apps/desk/src/api/index.ts
src/frontend/apps/desk/src/core/auth/Auth.tsx
src/frontend/apps/desk/src/core/auth/useAuthStore.tsx
src/frontend/apps/desk/src/custom-next.d.ts
src/frontend/apps/desk/src/features/members/__tests__/MemberGrid.test.tsx
src/frontend/apps/desk/src/features/members/__tests__/ModalRole.test.tsx
src/frontend/apps/desk/src/features/teams/__tests__/PanelTeams.test.tsx
src/helm/env.d/dev/values.desk.yaml.gotmpl

Until now, the front had to know at build time the url of the backend to be able to communicate with it.
It is not optimal because it means that we need multiple docker image (1 per environment) to have the app working, it is not very flexible.
This PR will make the frontend "environment free" by determining these urls at runtime.

♻️ Frontend env free

---

src/backend/core/models.py
src/backend/core/tests/test_models_invitations.py
src/mail/mjml/invitation.mjml
src/mail/package.json

The link in the email was pointing on the staging website. We now use a variable to target the current site setup in the database.
Based on this PR: https://github.com/numerique-gouv/impress/pull/56

♻️(mails) link email from current site

---

src/backend/mailbox_manager/admin.py
src/backend/mailbox_manager/api/serializers.py
src/backend/mailbox_manager/models.py
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_retrieve.py
src/backend/mailbox_manager/tests/test_models_maildomain.py
src/frontend/apps/desk/src/features/mail-domains/api/useCreateMailbox.tsx
src/frontend/apps/desk/src/features/mail-domains/api/useMailDomain.tsx
src/frontend/apps/desk/src/features/mail-domains/api/useMailboxes.tsx
src/frontend/apps/desk/src/features/mail-domains/components/MailDomainsContent.tsx
src/frontend/apps/desk/src/features/mail-domains/components/forms/CreateMailboxForm.tsx
src/frontend/apps/desk/src/features/mail-domains/components/panel/PanelItem.tsx
src/frontend/apps/desk/src/features/mail-domains/types.tsx
src/frontend/apps/desk/src/pages/mail-domains/[slug].tsx
src/frontend/apps/e2e/__tests__/app-desk/mail-domain-create-mailbox.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domain.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domains.spec.ts

With this change, instead of providing a UUID in the frontend application URL, we use the slug of a mail domain.
As a result, a URL that used to have the format `http://localhost:3000/mail-domains/6bbd8081-563a-4c5a-ae02-2785d18f2480` will look like `http://localhost:3000/mail-domains/domainfr`.
Each navigation button supposed to redirect to the view of a specific mail domain will embed the slug of the mail domain instead of its id. Also, every http request sent to the django API on the api/mail-domains/ path related to a specific domain and its mailboxes will use the mail domain slug instead of its id (as introduced in commit b4bafb6efbcfae4ed8a116061ee471a27737c41e).

🚧(app-regie) use mail domain slug for mail-domains navigation and requests

---

src/frontend/apps/desk/conf/default.conf
src/frontend/apps/desk/next.config.js
src/frontend/apps/e2e/__tests__/app-desk/footer.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domain.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domains.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/menu.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/teams-create.spec.ts

When we use the static mode, Next.js want that we build our team pages at build time. But we can't do that because users can create a team at runtime.
So we redirect thanks to ngnix when a user try to access a team page (`teams/[id]`) when we see that a team page is not found.
See more here: #127
[scrnli_6_27_2024_5-17-40 PM.webm](https://github.com/numerique-gouv/people/assets/25994652/b0685acf-e162-4035-96a9-c701615c77f2)

🐛(app-desk) router dynamic

---

src/frontend/apps/desk/src/features/teams/member-management/__tests__/MemberGrid.test.tsx
src/frontend/apps/desk/src/features/teams/member-management/components/MemberGrid.tsx

A recent change on the backend side ([#2ec29](https://github.com/numerique-gouv/people/commit/2ec292b)) changes the naming ordering params with a prefix "user__". 
We adapt the ordering name in the frontend to match the backend in order to have the sorting working.
[scrnli_6_28_2024_10-16-13 AM.webm](https://github.com/numerique-gouv/people/assets/25994652/50d3f633-4a46-43df-86ec-43e72680f3d9)

🏷️(frontend) adapt ordering name

---

src/backend/core/models.py
src/backend/core/tests/test_models_team_accesses.py
src/backend/core/tests/test_models_users.py

As suggested in #106 : Improve user model str representation. 
EDIT after Identity model removal  : 
- displays name if user has a name
- displays email if user has no name but an email
- displays sub otherwise

🧑‍💻(models) improve user str representation

---

README.md

README was not correctly updated after last major modif to the admin auth, resulting in confusion for users trying to log-in with email instead of sub. 
fixes #307

📝(readme) update admin credentials in README

---

src/backend/core/api/viewsets.py
src/backend/core/tests/team_accesses/test_api_team_accesses_list.py

Filter member by main identity name or email. 
Description...

✨(backend) allow to filter member on team access endpoint

---

.gitignore
Makefile
src/backend/pyproject.toml
src/backend/setup.py

Compute test coverage to make sure we test every line, especially upon adding a new feature.
- Should we add a run of coverage in the CI ? We could set a branch rule stating, say, that a branch cannot be merged if it makes coverage go under, say, 90% on main. WDYT ?

🩺(coverage) add config and make rule to compute coverage

---

src/backend/mailbox_manager/api/viewsets.py
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_create.py
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_delete.py

Pour l'instant on ne permet pas de supprimer un domaine. 
On implémentera 2 fonctionnements distincts 
- un admin ou un owner pourra supprimer un domaine si celui ci est en pending encore
- si le domain est en état actif alors le propriétaire pourra seulement le désactiver.

Suppression temporaire de la méthode DELETE sur le mail domain dans l'api

---

src/frontend/apps/desk/src/components/DropButton.tsx
src/frontend/apps/desk/src/cunningham/cunningham-style.css
src/frontend/apps/desk/src/features/language/LanguagePicker.tsx
src/frontend/apps/desk/src/features/mail-domains/components/panel/ItemList.tsx
src/frontend/apps/desk/src/features/mail-domains/components/panel/PanelItem.tsx
src/frontend/apps/desk/src/features/menu/MenuItems.tsx
src/frontend/apps/desk/src/features/teams/team-management/components/CardCreateTeam.tsx
src/frontend/apps/desk/src/features/teams/teams-panel/components/PanelActions.tsx
src/frontend/apps/desk/src/features/teams/teams-panel/components/TeamList.tsx
src/frontend/apps/desk/src/pages/teams/index.tsx
src/frontend/apps/e2e/__tests__/app-desk/keyboard-navigation.spec.ts

Keyboard navigation and some text colors needed improvement for better accessibility.
As stated in issues #282 and #283, more elements need to be navigable with the keyboard and some texts need a bigger contrast with their background.
Each element supposed to be visibly navigable with the keyboard (link, button, input, radio, checkbox) can be navigated.
- using the attribute tabindex / prop tabIndex to enable or disable keyboard navigation on an element
- visually highlighting the element with a blue outline surrounding it when it has `focus-visible` state
- creating the above two rules in root/parent components and the main CSS file to keep the code DRY.
AsyncSelect component can not use the style I have set. I did not do much on it as an async select component from Cunningham will soon …

Accessiblity and keyboard navigation

---

src/backend/core/tests/swagger/test_openapi_schema.py
src/backend/people/urls.py

Swagger was under /v1.0/swagger. I just wanna move it under /api/ where the rest of the API is.

🚚(api) move swagger under /api/

---

src/frontend/apps/desk/src/features/mail-domains/components/MailDomainsContent.tsx
src/frontend/apps/desk/src/features/mail-domains/types.tsx
src/frontend/apps/e2e/__tests__/app-desk/mail-domain-create-mailbox.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domain.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domains.spec.ts

- A user should not be allowed to create a mailbox when the ability is not granted.
The commit b637774 introduced rights restrictions on mailbox management in the backend. Now, a user not possessing the `post` ability on a mail domain can not create a mailbox.
- Each mailbox row in the tab should display the full name of its owner.
The commit c00c59b introduced the first and last names in mailbox data. We can now display them.
On /mail-domains/\<mail-domain-slug\> view:
- Hide the mailbox creation button if the post ability is falsy
- Show the full name of a mailbox owner for each row on the left column of the table
closes #324, closes #330, closes #294.

Mailbox creation and view improvements

---

src/backend/mailbox_manager/api/serializers.py
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_create.py
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_retrieve.py

✨(mail) add status on domain retrieve

---

src/backend/core/tests/team_accesses/test_api_team_accesses_list.py

Dans `test_api_team_accesses__list_find_members_by_email`.
Avec cette modification, on supprime les échecs aléatoires du test lorsque l'adresse attribuée à l'utilisateur source par FactoryBoy est considérée comme suffisamment similaire à BRUNE lors de la recherche par trigramme.
Fixes #326 (en partie: créer des issues pour les autres tests présentant des échecs aléatoires).
C'est un quick fix: pour une solution long terme il serait peut-être utile de revisiter ou alternativement de mieux documenter le choix de la recherche par trigramme pour le viewset TeamAccesses.

Corrige un test en échec intermittent

---

src/backend/core/admin.py
src/backend/mailbox_manager/admin.py

1/ Modification de l'affichage des users dans la vue liste. 
On affiche l'email si il existe à la place du sub.
2/ Ajout d'un inline pour gérer les rôles les noms de domaine sur le formulaire de création et édition d'un user

[ADMIN DJANGO] Amélioration affichage et gestion des users

---

src/backend/demo/defaults.py
src/backend/demo/management/commands/create_demo.py
src/backend/demo/tests/test_commands_create_demo.py

"Make demo" is very convenient. I use it on a regular basis when resetting my containers. Sole issue, it doesn't create domains and domain accesses. Let's fix that !
Add domains creation to "make demo" command. Update related test.

🔨(make) add domains to demo

---

CHANGELOG.md
docker-compose.yml
src/backend/core/migrations/0001_initial.py
src/backend/core/models.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/tests/test_models_mailboxes.py
src/backend/mailbox_manager/utils/dimail.py

dimail is called twice when creating a mailbox (once for the token,
and once for the post on mailbox endpoint). we want to clarify
the status_codes and messages of each error to inform user and ease debug

🐛(dimail) improve handling of dimail errors on failed mailbox creation

---

CHANGELOG.md
src/backend/people/settings.py
src/backend/pyproject.toml
src/helm/env.d/dev/values.desk.yaml.gotmpl
src/helm/env.d/preprod/values.desk.yaml.gotmpl
src/helm/env.d/production/values.desk.yaml.gotmpl
src/helm/env.d/staging/values.desk.yaml.gotmpl

Configure sentry dsn to monitor errors in sentry. 
In Joanie, Sentry DSN is set up in post_setup script. Here, I'll simply put it in settings for now, monitoring all environments to catch all potential errors. I'll remove environment later if we decide we don't need to track certain environments.
- [] item 1...
- [] item 2...

📈(monitoring) configure sentry monitoring

---

CHANGELOG.md
src/frontend/apps/desk/src/components/Modal.tsx
src/frontend/apps/desk/src/components/__tests__/Modal.test.tsx
src/frontend/apps/desk/src/cunningham/cunningham-style.css
src/frontend/apps/desk/src/features/language/LanguagePicker.tsx
src/frontend/apps/desk/src/features/mail-domains/components/ModalAddMailDomain.tsx
src/frontend/apps/desk/src/features/mail-domains/components/forms/CreateMailboxForm.tsx
src/frontend/apps/desk/src/features/teams/member-add/components/ModalAddMembers.tsx
src/frontend/apps/desk/src/features/teams/member-management/components/ModalDelete.tsx
src/frontend/apps/desk/src/features/teams/member-management/components/ModalRole.tsx
src/frontend/apps/desk/src/features/teams/team-management/components/ModalRemoveTeam.tsx
src/frontend/apps/desk/src/features/teams/team-management/components/ModalUpdateTeam.tsx
src/frontend/apps/e2e/__tests__/app-desk/keyboard-navigation.spec.ts

Based on manual acceptance tests and according to issue [#282](https://github.com/numerique-gouv/people/issues/282) comments, more work is needed to finish the keyboard navigation
- Prevent double focus on inner elements of language picker
- Prevent focus on modal elements and instead directly set the visible focus on the elements we decide
- Add a temporary fix to the language picker by manipulating the DOM and giving a tabIndex=-1 to the Cunningham Select component's parent div. This needs to be fixed directly in Cunningham Select as a contribution.
- Do the same to Cunningham Modal
https://github.com/user-attachments/assets/d11faa28-500f-4f0c-8864-1db8ba28b2f1
https://github.com/user-attachments/assets/9dd41c4d-96c1-40ed-b726-3bbb2ecf720c

🐛(frontend) fix keyboard navigation language picker

---

src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/tests/test_models_mailboxes.py
src/backend/mailbox_manager/utils/dimail.py

Separate headers request from mailbox request, to avoid catching the same exception twice.
Description...
- [] item 1...
- [] item 2...

♻️(dimail) separate headers request from mailbox request

---

CHANGELOG.md
docker-compose.yml
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/tests/test_models_mailboxes.py
src/backend/people/settings.py
src/helm/env.d/dev/values.desk.yaml.gotmpl

This PR is made to embark [dimail-api](4a135fb3382fcf042c2ec6700c1d4090a10c2cc9)'s container, automatically fetched from their repository, up-to-date with their `main` branch, and running in "FAKE" mode.  By using the real code, we ensure we are iso with their latest development, which will ease up interop development.
⚠️  The container we're using is currently built on our friends' `main` branch. We might want to rely on a more stable branch/keyword later.
⚠️ Our intention has shifted from earlier development. We first wanted to remove all mocks to use the real container directly in dev and tests. but then realized
-  this means OUR tests are broken and **we can't merge** if dimail's tests break / change their responses
- we're rather see dimail as an external dependency. We don't need …

🍱(dimail) embark dimail-api as container

---

CHANGELOG.md
src/backend/mailbox_manager/api/serializers.py
src/backend/mailbox_manager/factories.py
src/backend/mailbox_manager/models.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/tests/test_models_mailboxes.py
src/backend/mailbox_manager/utils/dimail.py

While working on the feature allowing to request a token for another dimail user, I realized business logic probably didn't belong to where we had put it (the model's save method). 
The purpose of this PR is to suggest a refacto of these elements.
Our resulting discussions aligned with best practices : we'll move all business logic from model to serializer. 
all API calls (direct and from front) will keep on triggering
expected 3rd party calls while admin actions will uniquely trigger
modifications in our database.

♻️(serializers) move business logic to serializers

---

CHANGELOG.md
src/backend/mailbox_manager/api/serializers.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/utils/dimail.py

Allow la regie to request a token for another dimail user, to better track who created/modified which resource.
Description...

✨(dimail) allow la regie to request a token for another user

---

src/helm/desk/templates/secrets.yaml

When new secret is added to backend secret, it's not sync at the beginning of argocd synchronisation and jobs are blocked. Theses new annotations fix this issue.

🔒️(helm) fix secret sync precedence

---

src/mail/mjml/new_mailbox.mjml

Link to the webmail was missing from notification email. This fixes html for link to correctly appear.
Description...
- [] item 1...
- [] item 2...

🐛(dimail) fix mail notification upon mailbox creation

---

CHANGELOG.md
src/frontend/apps/desk/src/core/__tests__/MainLayout.test.tsx
src/frontend/apps/desk/src/features/menu/MenuItems.tsx

The HTML semantics needed improvement: the menu items were buttons wrapped in li, which were themselves wrapped in link. This can cause inaccessibility issues to screen reader tools.
Just using a button inside a li.
https://github.com/user-attachments/assets/62322316-28e2-47c6-8926-26e3dcb67484
https://github.com/user-attachments/assets/68efb55a-390e-43f0-b0e7-411295e4b778
Closes #302

♿️(frontend) update left nav panel

---

CHANGELOG.md
src/backend/mailbox_manager/api/serializers.py
src/backend/mailbox_manager/api/viewsets.py
src/backend/mailbox_manager/models.py
src/backend/mailbox_manager/tests/api/mail_domain_accesses/test_api_mail_domain_accesses_update.py

Allow to update (PUT, PATCH) an access.
Role can be change only to a role available
depending to the authenticated user.

✨(backend) domain accesses update API

---

CHANGELOG.md
src/backend/mailbox_manager/api/serializers.py
src/backend/mailbox_manager/api/viewsets.py
src/backend/mailbox_manager/tests/api/mail_domain_accesses/test_api_mail_domain_accesses_create.py

Description...
Description...
- [] item 1...
- [] item 2...

API create mail domain access

---

CHANGELOG.md
src/backend/people/settings.py

Fix following warning messages :
- You have not set a value for the SECURE_HSTS_SECONDS setting.
- Your SECURE_SSL_REDIRECT setting is not set to True.

🔧(backend) fix configuration to avoid different ssl warning

---

CHANGELOG.md
src/backend/mailbox_manager/api/permissions.py
src/backend/mailbox_manager/api/viewsets.py
src/backend/mailbox_manager/models.py
src/backend/mailbox_manager/tests/api/mail_domain_accesses/test_api_mail_domain_accesses_delete.py

Il me reste à refactoriser un peu la gestion des permissions à cause du get_abilities sur le MailDomainAccess

✨(backend) domain accesses delete API

---

CHANGELOG.md
src/backend/people/settings.py
src/helm/desk/templates/secrets.yaml
src/helm/env.d/preprod/values.desk.yaml.gotmpl
src/helm/env.d/production/values.desk.yaml.gotmpl
src/helm/env.d/staging/values.desk.yaml.gotmpl

We modify multiples things :
* settings.py in order to manage the new way to send email with the scaleway gateway
* helm template to manage new mandatory secret
* helm configuration for staging/preprod/production

🔧(bakend) use new scaleway email gateway

---

CHANGELOG.md
src/frontend/apps/desk/src/features/mail-domains/access-management/components/ChooseRole.tsx
src/frontend/apps/desk/src/features/mail-domains/access-management/components/ModalRole.tsx
src/frontend/apps/desk/src/features/mail-domains/access-management/components/__tests__/ChooseRole.test.tsx
src/frontend/apps/desk/src/features/mail-domains/access-management/components/__tests__/ModalRole.test.tsx
src/frontend/apps/desk/src/features/mail-domains/domains/types.ts

- The form to modify the role of an administrator is not good while the API is good.
We should have the administrator role selected and the viewer role available and possibly the owner role available if the API returns it.
Same problem for the reader role.
- Delete readonly message and fields
close #448

🐛(frontend) Bug manage access role

---

CHANGELOG.md
src/backend/core/authentication/backends.py
src/backend/core/tests/authentication/test_backends.py
src/backend/people/settings.py

Some OIDC identity providers may provide a random value in the "sub" field instead of an identifying ID. In this case, it may be a good idea to fallback to matching the user on its email field.
Adaptation of https://github.com/numerique-gouv/impress/pull/303
Needs fixing when brainjuice will be available
Description...
- [] item 1...
- [] item 2...

🛂(backend) match email if no existing user matches the sub

---

CHANGELOG.md
src/backend/core/authentication/backends.py
src/backend/core/tests/authentication/test_backends.py

When a user is disabled and tries to login, we don't want the user to be duplicated, the user should not be able to login.
Fixes https://github.com/numerique-gouv/people/issues/455

🛂(backend) do not duplicate user when disabled

---

CHANGELOG.md
src/backend/core/api/viewsets.py
src/backend/core/tests/test_api_config.py
src/frontend/apps/e2e/__tests__/app-desk/config.spec.ts

Add release version deployed to config endpoint
in order to display release info in La Régie footer.
Fixes #459

✨(api) add RELEASE version on config endpoint

---

CHANGELOG.md
src/frontend/apps/desk/src/__tests__/pages.test.tsx
src/frontend/apps/desk/src/core/__tests__/MainLayout.test.tsx
src/frontend/apps/desk/src/core/config/types.ts
src/frontend/apps/desk/src/features/footer/Footer.tsx
src/frontend/apps/e2e/__tests__/app-desk/footer.spec.ts

In order to see the version number pushed into production

✨(frontend) show version number in footer

---

CHANGELOG.md
src/backend/people/settings.py

errors were sent to sentry twice, they should now appear only once
https://docs.sentry.io/platforms/python/integrations/django/#issue-reporting
"Logs emitted by any logger will be recorded as breadcrumbs by the Logging integration (this integration is enabled by default)."
https://docs.sentry.io/platforms/python/integrations/default-integrations/
" To disable all system integrations, set default_integrations=False when calling init()."
Description...
- [] item 1...
- [] item 2...

🐛(sentry) fix duplicated sentry errors

---

CHANGELOG.md
src/backend/pyproject.toml
src/frontend/apps/desk/package.json
src/frontend/apps/e2e/package.json
src/frontend/package.json
src/frontend/packages/eslint-config-people/package.json
src/frontend/packages/i18n/package.json
src/helm/env.d/preprod/values.desk.yaml.gotmpl
src/helm/env.d/production/values.desk.yaml.gotmpl

🔖(minor) release version 1.4.0

---

CHANGELOG.md

e2e sharding was merged with its changelog in the wrong release. Fixes that
Description...
- [] item 1...
- [] item 2...

🐛(changelog) fix changelog order

---

.github/workflows/people.yml
CHANGELOG.md
src/backend/demo/management/commands/create_demo.py
src/frontend/apps/e2e/playwright.config.ts

At present E2E tests are more of a burden on the team than they are helping with quality, due to instability which I believe was mainly caused by parallel workers, but these problems were hidden by the two-retries policy.
This PR fixes some of the stability issues but also argues for following the testing philosophy **"fail fast"**.
Rather than "retrying flaky tests" I propose seeing any test failure, even intermittent, as a sign of a potential problem. The right thing to do with a potential problem is not, as it were, to sweep it under the rug, but to fix it for the future.
If a test is truly flaky then it needs to be fixed or removed - E2E tests need to pull their weight, given their cost in terms of longer feedback loops.
This PR
- rolls back the "multiple workers in CI " change made …

Improve E2E tests: fix stability issues, tighten controls

---

src/frontend/apps/e2e/playwright.config.ts

Tiny PR that was intended to aid in debugging E2E test duration issues, but also has a more tangible benefit of helping identify slow tests.
By default the test runner uses the `null` reporter for outputting to stdio. I suspect that this suppresses output in CI, so that if all tests run successfully, *nothing* gets output at all (until an eventual cancellation for exceeding the time budget). But it's also possible that the runner is somehow getting stuck after emitting a line like `Running 37 tests using 1 worker, shard 1 of 4`.
Using the `list` reporter distinguishes between the two cases. If the job is interrupted, we can know how many tests were run. And as a nice bonus, we get timings for each separate test in the run, which can be useful in fixing slow tests.

Use list reporter in addition to html

---

CHANGELOG.md
src/backend/core/api/viewsets.py
src/backend/core/tests/teams/test_core_api_teams_list.py
src/frontend/apps/desk/next-env.d.ts
src/frontend/apps/desk/src/features/teams/team-management/api/useTeams.tsx
src/frontend/apps/desk/src/features/teams/teams-panel/__tests__/PanelTeams.test.tsx
src/frontend/apps/desk/src/features/teams/teams-panel/components/TeamList.tsx
src/frontend/apps/e2e/__tests__/app-desk/keyboard-navigation.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/teams-panel.spec.ts
src/frontend/yarn.lock

For frontend pagination is useless for teams,
so we remove it.
fixes [#497](https://github.com/numerique-gouv/people/issues/497)

🔥(teams) remove pagination of teams listing

---

.github/workflows/docker-hub.yml
CHANGELOG.md
Dockerfile

Add a security scan for CVE with trivy

✨(ci) add security scan

---

CHANGELOG.md
src/backend/pyproject.toml

To reduce attack surface and dependency updates, remove listed dependencies that are not actually in use.
Remove url-normalize which is not referenced anywhere

⬆️(dependencies) remove unneeded dependencies

---

CHANGELOG.md
src/mail/mjml/new_mailbox.mjml

In confirmation email of mailbox creation,
button "Go to La Messagerie" disappears on Outlook. We try to fix here this display bug.

🐛(mail) fix button display on outlook

---

CHANGELOG.md
src/backend/mailbox_manager/admin.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/tests/test_utils_dimail_client.py
src/backend/mailbox_manager/utils/dimail.py

I want to synchronize mailboxes FROM dimail TO people, by instance if a domain has already been existing for a while (i.e. beta.gouv)
I don't think this synchronization needs to be on a CRON. Create a route below /domains/ to call for a synchronization.

✨(dimail) synchronize mailboxes from dimail to our db

---

.github/workflows/docker-hub.yml

Separate security scan from build-and-push, so we can make it optional in CI; this was the case for the backend but frontend was overlooked…
Trivy scans still occasionally fail for wrong reasons (but are still useful despite that).

Separate security scan for frontend too

---

.github/workflows/people.yml
CHANGELOG.md
docker-compose.yml
docs/interoperability/dimail.md
src/backend/mailbox_manager/api/serializers.py
src/backend/mailbox_manager/management/commands/setup_dimail_db.py
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_create.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/utils/dimail.py
src/backend/people/settings.py
src/helm/env.d/dev/values.desk.yaml.gotmpl

Send domain creation request to dimail when someone creates a domain in people.
Description...
...

✨(dimail) send domain creation request to dimail

---

.github/workflows/docker-hub.yml
src/backend/core/api/viewsets.py
src/backend/core/tests/test_api_config.py
src/backend/people/settings.py
src/frontend/apps/desk/.prettierignore
src/frontend/apps/desk/src/__tests__/pages.test.tsx
src/frontend/apps/desk/src/core/__tests__/MainLayout.test.tsx
src/frontend/apps/desk/src/core/config/types.ts
src/frontend/apps/desk/src/features/footer/Footer.tsx
src/frontend/apps/desk/version.json
src/frontend/apps/e2e/__tests__/app-desk/config.spec.ts

Display version information in the app's footer to help acceptance testing and debugging.
Fixes #510
This supplements the release process. We inject Github metadata into two version.json files; the 'version' value will be filled with `github.ref_name`, which will depend on the type of event, for release tag events it should be the same as the release tag (i.e. the app version). This should make version information available to the /config endpoint on any push, and the frontend should display the backend version.
Relevant documentation: [Accessing contextual information about workflow runs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context)

Create version.json files on both backend and frontend on push

---

CHANGELOG.md
src/backend/core/authentication/backends.py
src/backend/core/tests/authentication/test_backends.py

When we use the feature to get Organization registration number, the claim contains this value and it does not match with any user field.
BUG seen in [LA-REGIE-BACKEND-16](https://sentry.incubateur.net/organizations/betagouv/issues/133323/)
I switched to a whitelist instead of a blacklist (and two loops, with an if condition on each)

🚑️(backend) fix claim contains non user field

---

CHANGELOG.md
src/backend/core/admin.py

User fields has to be listed, this one was forgotten in the "add organization" commit...

🐛(admin) add organization on user

---

CHANGELOG.md
src/backend/admin/__init__.py
src/backend/admin/apps.py
src/backend/admin/sites.py
src/backend/admin/templates/admin/base_site.html
src/backend/people/settings.py
src/helm/env.d/production/values.desk.yaml.gotmpl
src/helm/env.d/staging/values.desk.yaml.gotmpl

This allows to use custom colors according to environment.
FIXES #430

💄(admin) allow header color customization

---

CHANGELOG.md
src/backend/core/api/client/serializers.py
src/backend/core/api/client/viewsets.py
src/backend/core/factories.py
src/backend/core/models.py
src/backend/core/tests/organizations/__init__.py
src/backend/core/tests/organizations/test_core_api_organizations_retrieve.py
src/backend/core/tests/organizations/test_core_api_organizations_update.py
src/backend/core/tests/test_api_users.py
src/backend/people/api_urls.py

This provides a way to get information about organization and update their name for administrators.
This will allow the frontend to display data about organization when displaying a user or a list of users.
Add `Organization` serializers and viewset. The frontend integration will be done later (when we know were we want to display any of this).

✨(organization) add API endpoints

---

src/helm/env.d/production/values.desk.yaml.gotmpl

Changed: api.ox.numerique.gouv.fr -> api.ovhprod.dimail1.numerique.gouv.fr

Change production endpoint

---

src/helm/env.d/preprod/values.desk.yaml.gotmpl
src/helm/env.d/staging/values.desk.yaml.gotmpl

Change dev endpoints: api.dev.ox.numerique.gouv.fr -> api.ovhdev.dimail1.numerique.gouv.fr

Change dev endpoints

---

docker/auth/realm.json
docs/testsE2E.md
src/backend/demo/management/commands/create_demo.py
src/frontend/apps/e2e/__tests__/app-desk/common.ts
src/frontend/apps/e2e/__tests__/app-desk/member-delete.spec.ts

The user full name was not the same, it would induce flaky test, while the user name is updated at user login from the KC data.
Use `E2E` as first name everywhere.

✅(e2e) sync keycloak users w/ backend users

---

.github/workflows/people.yml
CHANGELOG.md
docker-compose.yml
src/backend/mailbox_manager/api/client/serializers.py
src/backend/mailbox_manager/api/client/viewsets.py
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_create.py
src/backend/mailbox_manager/tests/api/mail_domain_accesses/test_api_mail_domain_accesses_create.py
src/backend/mailbox_manager/utils/dimail.py

Automatically send user creation and allow creation requests to dimail
upon creating domain access.
Description...

✨(dimail) automate allows requests to dimail when creating domain accesses

---

CHANGELOG.md
src/backend/mailbox_manager/utils/dimail.py

Fix 422 Unprocessable Entity error returned
by dimail because of some missing data sent.

🐛(mailbox) fix activate mailbox feature

---

CHANGELOG.md
src/backend/mailbox_manager/admin.py

Fix creation of new role to manage mail domain on admin interface

🐛(backend) fix manage roles on domain admin view

---

CHANGELOG.md
src/backend/core/api/client/serializers.py
src/backend/core/api/client/viewsets.py
src/backend/core/models.py
src/backend/core/tests/contacts/test_core_api_contacts_create.py
src/backend/core/tests/contacts/test_core_api_contacts_delete.py
src/backend/core/tests/contacts/test_core_api_contacts_list.py
src/backend/core/tests/contacts/test_core_api_contacts_retrieve.py
src/backend/core/tests/contacts/test_core_api_contacts_update.py

Update the `contacts` endpoint to use the "get_abilities" methods to allow frontend to know which actions are available along with the permission access to the API.

✨(contacts) add "abilities" to API endpoint data

---

CHANGELOG.md
src/backend/mailbox_manager/api/client/viewsets.py
src/backend/mailbox_manager/tests/api/mail_domain_accesses/test_api_mail_domains_accesses_get_available_users.py

closes [#508](https://github.com/numerique-gouv/people/issues/508)

✨(maildomain_access) add API endpoint to search users

---

CHANGELOG.md
src/frontend/apps/desk/src/__tests__/pages.test.tsx
src/frontend/apps/desk/src/pages/index.tsx
src/frontend/apps/e2e/__tests__/app-desk/config.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domains.spec.ts

We try to detect the landing page according to user permissions (abilities) instead of just the configuration setting.
This will be improved when the homepage is developed

💄(frontend) redirect home according to abilities

---

src/frontend/apps/e2e/__tests__/app-desk/mail-domain.spec.ts

The URL may or may not include the "page" query parameter.
Do not enforce the "page" parameter when mocking the API.

✅(e2e) fix flaky test

---

CHANGELOG.md
src/backend/core/models.py
src/backend/core/plugins/__init__.py
src/backend/core/plugins/base.py
src/backend/core/plugins/loader.py
src/backend/people/settings.py
src/backend/plugins/__init__.py
src/backend/plugins/organizations.py
src/backend/plugins/tests/__init__.py
src/backend/plugins/tests/organizations/__init__.py
src/backend/plugins/tests/organizations/test_name_from_siret_organization_plugin.py
src/helm/env.d/dev/values.desk.yaml.gotmpl
src/helm/env.d/preprod/values.desk.yaml.gotmpl
src/helm/env.d/production/values.desk.yaml.gotmpl
src/helm/env.d/staging/values.desk.yaml.gotmpl

This adds the plugin system to easily manage Organization related customization. This first plugin tries (best effort) to get a proper name for the Organization, using its SIRET. 
This is French specificity but another plugin can be defined for other cases.
This is a very naive implementation.

✨(organizations) add siret to name conversion

---

CHANGELOG.md
src/backend/mailbox_manager/api/client/serializers.py
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_create.py
src/backend/mailbox_manager/utils/dimail.py

Lors de la création d'un nouveau domaine, un appel à dimail est réalisé pour créer le user et l'accès coté dimail avant même la création du rôle owner sur le domaine.
Lorsque la création user/allow coté dimail échoue, le rôle owner n'est pas créé de notre coté. Par conséquent le domaine est créé mais invisible sur l'interface de l'utilisateur. 
Il va alors probablement retenter de créer un domaine avec le même nom et là il aura une erreur lui disant qu'il existe déjà.
Pour éviter ça on s'assure de créer le rôle owner de notre coté malgré l'echec dimail, 
on passe le status du domain en failed et on log un message d'erreur.

🐛(maildomain) fix domain access creation

---

docker-compose.yml

upgrade to 0.0.20 to fix weird anonymous admin behaviour when database not initialized.
Weird behaviour in question : 
Dimail would allow every database change when user table empty. This means that, when forgetting to setup your dimail db, you could create domains, users and only fail after that (by example, for an allows), where you would be rejected because your credentials (used for the first time) would not match any user.

⬆️(dimail) upgrade dimail to 0.0.20

---

CHANGELOG.md
src/frontend/apps/desk/src/features/mail-domains/mailboxes/api/useUpdateMailboxStatus.tsx
src/frontend/apps/desk/src/features/mail-domains/mailboxes/components/MailDomainsActions.tsx
src/frontend/apps/desk/src/features/mail-domains/mailboxes/components/MailDomainsContent.tsx
src/frontend/apps/desk/src/features/mail-domains/mailboxes/components/__tests__/MailDomainsContent.test.tsx
src/frontend/apps/desk/src/features/mail-domains/mailboxes/types.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domain-create-mailbox.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domain.spec.ts

Permet de désactiver/réactiver une mailbox avec modal de confirmation pour la désactivation car perte de données coté dimail.
Permet de créer des boites mails en pending pour un domaine non actif encore

Front pour les dernières évols sur les noms de domains/mailboxes

---

CHANGELOG.md
src/backend/core/migrations/0001_initial.py
src/backend/core/models.py

The use of a lazy function here make the Django migration detector to generate a migration every time we run `makemigrations`. 
This is not mandatory to have a lazy here as the settings are loaded once at runtime beginning.
As the choices makes noop migrations, we directly use the setting in the initial migration.

🧑‍💻(user) fix the `User.language`

---

CHANGELOG.md
docker/auth/realm.json
src/backend/core/api/client/serializers.py
src/backend/core/tests/users/test_api_users_list.py
src/backend/core/tests/users/test_api_users_retrieve.py
src/backend/people/settings.py
src/backend/pyproject.toml
src/frontend/apps/e2e/__tests__/app-desk/siret.spec.ts
src/helm/env.d/dev/values.desk.yaml.gotmpl

Improve developer experience by making local dev resemble production conditions more closely.
We can now find organization data as provided by ProConnect in `user_info`, specifically SIRET.
Otherwise local development would be blind to registration ID fields (e.g. SIRET)… and these will become more important as we start dealing with a variety of organizations both private and public (such as French communes).
This is mostly to have a convenient way of testing the delivered feature, via an API-oriented E2E test. This isn't entirely satisfactory: as this is a very important feature, we should be able to unit test it. The E2E test depends on technical details such as the fact that we use Keycloak to simulate the ProConnect flow.
This is necessary for several backend tests that query the …

Add siret attribute and mapper to Keycloak

---

CHANGELOG.md
src/backend/mailbox_manager/api/client/serializers.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py

When we try to create a duplicate email, a request to dimail is sent despite a reject on our side.
To solve this issue, we call mailbox creation first to benefit from validation of our Django model.
Mailbox creation try was called too late after dimail call. So in attempt to create a duplicated email a request to dimail was sent despite a failure in our side.

🐛(backend) fix dimail call despite mailbox creation failure on our side

---

src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/utils/dimail.py

Logic was broken when attempting to duplicate mailboxes, where infos were sent to dimail before checking for uniqueness.
I'd rather add this logic to a `validate` function in serializer, but that would require some heavier refacto (addition of domain in serializer or at least in context)

🐛(mailboxes) fix logic when attempting to duplicate mailboxes

---

src/backend/core/tests/contacts/test_core_api_contacts_list.py

Fixed a test that would sometimes fail because of randomly assigned auth user name being too close to tested names (assert would then find 2 results instead of 1). Setting the name of auth user should fix the issue permanently.
Description...

🐛(tests) fix flaky back-end test

---

CHANGELOG.md
src/frontend/apps/desk/src/features/mail-domains/mailboxes/components/MailDomainsActions.tsx

Do not display disable/enable mailbox button
for viewers.
Only owner and admin can manage mailbox and use
this button.
fix #631

🐛(frontend) fix disable mailbox button display

---

src/backend/mailbox_manager/admin.py

mark local_part and domain as read-only fields in admin, in order to prevent mistakes/temptation. For now, if an local part needs modification, you can simply delete/recreate the email you want. Changing the domain is a bigger operation that cannot be settled simply by changing it Django db.
Description...
- [] item 1...
- [] item 2...

🧑‍💻(admin) add read-only fields to mailbox admin

---

CHANGELOG.md
docker/auth/realm.json
src/backend/people/settings.py
src/backend/plugins/organizations.py
src/backend/plugins/tests/organizations/test_name_from_siret_organization_plugin.py
src/frontend/apps/desk/src/core/auth/api/types.ts
src/frontend/apps/desk/src/features/header/AccountDropdown.tsx
src/frontend/apps/e2e/__tests__/app-desk/siret.spec.ts
src/helm/env.d/preprod/values.desk.yaml.gotmpl
src/helm/env.d/production/values.desk.yaml.gotmpl

New users from communes should be able to make sense of what they can do with Régie.
When arriving at Régie from ProConnect, make sure things are set up properly:
- lookup the Commune using the provided SIRET
- ensure the Organization is created with the commune's name
Fixes #610

Fetch and display commune name

---

CHANGELOG.md
src/backend/core/admin.py

This allows admin user to run the post creation plugins from the organization list.

✨(organization) add admin action for plugin

---

src/backend/mailbox_manager/tests/fixtures/dimail.py
src/backend/mailbox_manager/tests/test_admin_actions.py
src/backend/mailbox_manager/tests/test_utils_dimail_client.py

Add missing test case and add a new fake data
for fetch domain status from dimail

✅(dimail) improve fetch domain status tests

---

CHANGELOG.md
src/backend/mailbox_manager/utils/dimail.py

Fixes "NoneType: None" log appearing in debug mode.

🧑‍💻(dimail) remove 'NoneType: None' log

---

CHANGELOG.md
src/backend/core/api/client/viewsets.py
src/backend/core/tests/contacts/test_core_api_contacts_list.py

Sometimes emails generated by faker in data field match search. So it's necessary to create contacts with empty data field.
closes #605

🐛(backend) fix flaky test with search contact

---

.github/workflows/docker-hub.yml

Changing the deployment repository broke the automatic deployment of the main branch. This commit fixes it.

🐛(ci) fix argocd webhook to auto deploy on staging

---

CHANGELOG.md
Makefile
src/backend/mailbox_manager/management/commands/fetch_domain_status.py
src/backend/mailbox_manager/tests/commands/test_fetch_domain_status.py

Add a management command for a future cron to
to check and update regularly domains status
from dimail.

✨(dimail) management command to fetch domain status

---

CHANGELOG.md
src/backend/mailbox_manager/tests/test_utils_dimail_client.py
src/backend/mailbox_manager/utils/dimail.py

Importing mailboxes creates pending mailboxes ... but these mailboxes are already active and, for most, functional. We thus mark them as "enabled".
Description...

🐛(dimail) fix imported mailboxes should be enabled instead of pending

---

scripts/release.py

One of instructions was in a wrong place.
Release tag on github belongs to the project part.

✨(scripts) improve release script

---

CHANGELOG.md
src/frontend/apps/desk/next-env.d.ts
src/frontend/apps/e2e/__tests__/app-desk/config.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/keyboard-navigation.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domain-create-mailbox.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domain.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domains.spec.ts
src/frontend/apps/e2e/playwright.config.ts

Several E2E tests were suffering from a race condition problem. The race condition affected setting up mocked API calls with `page.route` and navigation to the front page of Desk. Specifically, the call to `page.goto('/')` was made _before_ the call to `page.route`, without caring to synchronize the two. This meant that, at random, we could possibly have the API calls made by the front page complete before the mocks were in place, leading to a test failure.
This PR aims to eliminate this source of intermittent CI failures, which are always obnoxious and lead to a waste of time (when we investigate why the build failed), of resources (when we have to rerun jobs) and more importantly a loss of confidence in the test suite.
We systematically have the calls to `page.route` take place …

🐛(frontend) improve e2e tests avoiding race condition from mocks

---

CHANGELOG.md
src/backend/mailbox_manager/tests/commands/test_fetch_domain_status.py
src/backend/mailbox_manager/tests/fixtures/dimail.py
src/backend/mailbox_manager/tests/test_admin_actions.py
src/backend/mailbox_manager/tests/test_utils_dimail_client.py
src/backend/mailbox_manager/utils/dimail.py

 Adapt fetch domain status to manage action required cases 

---

CHANGELOG.md
src/backend/core/api/client/viewsets.py
src/backend/core/api/permissions.py
src/backend/core/models.py
src/backend/core/tests/teams/test_core_api_teams_create.py
src/backend/core/tests/users/test_api_users_retrieve.py
src/frontend/apps/desk/src/features/teams/teams-panel/__tests__/PanelTeams.test.tsx
src/frontend/apps/desk/src/features/teams/teams-panel/components/PanelActions.tsx
src/frontend/apps/desk/src/features/teams/teams-panel/components/TeamList.tsx
src/frontend/apps/e2e/__tests__/app-desk/config.spec.ts

The frontend should not display "add team" actions when the user has not the ability.
When we don't allow the user to see the team creation button, we also want to disable the corresponding API.

🚑️(teams) do not display add button when disallowed

---

CHANGELOG.md
src/backend/mailbox_manager/api/client/serializers.py
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_create.py
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_retrieve.py

Return number of mailboxes of a domain in our API.

✨(api) add count mailboxes to MailDomain serializer

---

src/helm/desk/Chart.yaml
src/helm/desk/README.md
src/helm/desk/templates/backend_deployment.yaml
src/helm/desk/templates/frontend_deployment.yaml
src/helm/desk/values.yaml

In order to avoid a service interruption during a Kubernetes (k8s)upgrade, we add a Pod Disruption Budget (PDB) to deployments.

🔧(helm) add pdbs to deployments

---

CHANGELOG.md
Makefile
docker-compose.yml
docker/auth/realm.json
env.d/development/france.dist
src/backend/core/models.py
src/backend/core/plugins/base.py
src/backend/core/plugins/loader.py
src/backend/people/settings.py
src/backend/plugins/organizations.py
src/backend/plugins/tests/organizations/test_commune_creation.py
src/backend/plugins/tests/organizations/test_name_from_siret_organization_plugin.py
src/frontend/apps/e2e/__tests__/app-desk/domain-provisioning.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/siret.spec.ts
src/helm/env.d/dev-keycloak/values.desk.yaml.gotmpl
src/helm/env.d/dev/values.desk.yaml.gotmpl

Completing #583, ensure users from communes can do something meaningful upon onboarding: create a default domain for them, so that they can create mailboxes
- Segregate France-specific dev settings so that they are easy to disable for other countries
- Call Scaleway API upon organization creation to provision subzone and email-related DNS entries
- Extend plugin mechanism to grant admin access to the newly created domain in Dimail
- Introduce ApiCall object, to avoid mocking and anticipating task queuing

Automate domain creation

---

src/backend/plugins/organizations.py

Use a real email to contact support in case
of actions required on the domain in collectivite.fr

🐛(plugin) fix support email

---

src/backend/mailbox_manager/models.py
src/backend/mailbox_manager/tests/test_utils_dimail_client.py

Order by last created models MailDomain, Mailbox and MailDomainAccess.

🧑‍💻(domains) change default ordering

---

src/backend/people/settings.py

Make it possible to set logging configuration on a per-deployment basis in production, so we can actually see our application logs in our production environment.
Currently, LOGGING is defined only on the Development class. This means that the Staging, PreProduction and Production classes, which are used in our prod environments, do not define any logger options. As a result, our production environments use the default Python logging configuration: a log level of WARNING, and no timestamping of logs, among other things.
This PR moves up the LOGGING definition, to the Base class, this way Production and subclasses will inherit it. This will make INFO the default log level for the root and app loggers. This definition includes an environment variable mapping, so we can still configure a …

:loud_sound:(prod) move logging config up to Base configuration class

---

src/frontend/apps/desk/src/features/mail-domains/domains/components/ModalAddMailDomain.tsx
src/frontend/apps/desk/src/i18n/translations.json

The domain of support email suggested was
the same as the example domain name
suggested below.
This was a bit confusing because if the
domain is broken we need to contact someone
with a working email address.

💄(frontend) change support email example

---

Dockerfile

Added temporary root privileges to update OpenSSL libraries. Upgrades libssl3 and libcrypto3 to 3.3.3-r0 to fix HIGH severity vulnerability. Properly switches back to nginx user after updates. Maintains unprivileged execution while addressing security concern affecting RFC7250 Raw Public Keys authentication.
Security: CVE-2024-12797
Fix temporaire d'Antoine [ici](https://github.com/suitenumerique/meet/commit/b5037db685803b9189f7787156a6533283114b90)

🔒️(docker) patch libssl3 and libcrypto3 to address CVE-2024-12797

---

.github/workflows/people.yml
src/frontend/apps/e2e/playwright.config.ts

Step labeled "Install Playwright browsers" in CI is taking at least two minutes, often longer, sometimes causing failures. It's not actually necessary as we are only using the Chromium engine and Chrome is in our base image.
Use Chrome that's already installed.
Inspired by https://github.com/microsoft/playwright/issues/23388

⚡️(ci) save time on CI by not downloading already present browser

---

src/backend/plugins/organizations.py
src/backend/plugins/tests/organizations/test_commune_creation.py
src/frontend/apps/e2e/__tests__/app-desk/domain-provisioning.spec.ts

Complete automated domain provisioning that was _almost_ correct 😅 
~~Automatically created domains are now set to active, and a user created in Dimail. Also add an E2E test showing it's possible to immediately create mailboxes on such domains.~~
Amended proposal and implementation after discussing with @sdemagny - only create the user in Dimail, leave the status as Pending (the user can rerun the check at any time), comment out the E2E test for now.

🐛(communes) add missing user creation and status in domain provisioning

---

CHANGELOG.md
src/backend/plugins/organizations.py

Avoid 500s when requesting new domains from Dimail at commune creation time.
The domain creation endpoint will sometimes take longer than 5s to complete, so we increase timeouts.

👽️(dimail) increase timeout value for API calls

---

docs/local_development_kube.md

I'm trying to install tilt and doc seems outdated/Mac-only. This is an attempt at making it better, especially for linux users.
Description...

📝(tilt) improve tilt doc

---

Makefile

Preserve developer experience (esp. for newly onboarded devs)
Removal of Playwright browsers installation is a win for CI but
not a reason to degrade developer experience, so we install them
locally as part of the bootstrap process.

🧑‍💻(bootstrap) install playwright browsers for local dev

---

renovate.json

Get [Renovate/JS](https://github.com/suitenumerique/people/pull/735) unstuck.
Version 4.1.0 of @hookforms/resolvers breaks Zod resolvers, tell Renovate to ignore it until the issue is fixed.

📌(renovate) ignore @hookform/resolvers until issue fixed

---

src/backend/core/tests/swagger/test_openapi_schema.py
src/backend/people/settings.py

activate swagger in staging for devs from other teams to build interop more easily
Activate ONLY on staging because the memory leaks issue is **not** fixed. See #673 
(could it simply be a USE_SWAGGER = True ? 🤔 suspicious)

🔧(swagger) activate swagger in staging

---

src/backend/people/settings.py
src/backend/pyproject.toml

add drf_spectacular_sidecar to correctly collect swagger upon collectstatic
Description...

🔧(api) allow swagger collection

---

CHANGELOG.md
src/backend/mailbox_manager/migrations/0023_mailbox_email_mailbox_last_login_mailbox_password.py

Fix AttributeError
'Mailbox' object has no attribute 'get_email'

🐛(mailbox) fix migration to fill dn_email field

---

src/backend/mailbox_manager/api/client/serializers.py
src/backend/mailbox_manager/api/client/viewsets.py
src/backend/mailbox_manager/factories.py
src/backend/mailbox_manager/migrations/0024_domaininvitation.py
src/backend/mailbox_manager/models.py
src/backend/mailbox_manager/signals.py
src/backend/mailbox_manager/tests/api/invitations/test_api_domain_invitations_create.py
src/backend/mailbox_manager/tests/api/invitations/test_api_domain_invitations_list.py
src/backend/mailbox_manager/tests/api/invitations/test_api_domain_invitations_retrieve.py
src/backend/mailbox_manager/tests/models/test_invitations.py
src/backend/mailbox_manager/urls.py

All models relacted to mail domain are prefixed
with "MailDomain". Do the same for mail domain invitations.

♻️(backend) Rename DomainInvitation

---

src/backend/mailbox_manager/factories.py

Avoid random CI failures unrelated to the contents of commits or PRs.
MailDomain fixtures now use a boring non-repeating sequence. If you ask for a batch of domains, they will be domain1.com, domain2.com, and so on. This means that MailDomainFactory.create_batch(N) will always return exactly N different names, although similar to each other.
No longer will the occasional random CI failure inject excitement into our workdays; but fear not, there will remain other occasions to enjoy the art of debugging.
Fixes #699

🐛(tests) change domain name factory to be more boring but reliable

---

CHANGELOG.md
src/backend/mailbox_manager/api/client/serializers.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/utils/dimail.py
src/backend/people/settings.py

Don't forget to translate mail content before sending.

🐛(mailbox) fix mailbox creation email language

---

.gitignore
CHANGELOG.md
Makefile
docker-compose.yml
src/backend/mailbox_manager/tasks.py
src/backend/mailbox_manager/tests/test_tasks.py
src/backend/people/__init__.py
src/backend/people/settings.py
src/backend/pyproject.toml
src/helm/desk/Chart.yaml
src/helm/desk/templates/_helpers.tpl
src/helm/desk/templates/celery_beat_deployment.yaml
src/helm/desk/templates/celery_worker_deployment.yaml
src/helm/desk/values.yaml
src/helm/env.d/dev-keycloak/values.desk.yaml.gotmpl
src/helm/env.d/dev/values.desk.yaml.gotmpl

Add celery crontab to check and update domains status. This task calls dimail API.
TODO: 
FIXES #695

✨(mailbox_manager) add shedule task to fetch domains status

---

Makefile

The `i18n-generate` make command was not downloading the pot from crowdin before the Django `makemessages` resulting in a pot file never updated.
Now:
```
> make -n i18n-generate
DOCKER_USER=1000:1000 docker compose run --rm crowdin crowdin download sources -c crowdin/config.yml
DOCKER_USER=1000:1000 docker compose run --rm app-dev python manage.py makemessages -a --keep-pot
cd ./src/frontend && yarn i18n:extract
> make -n back-i18n-generate
DOCKER_USER=1000:1000 docker compose run --rm crowdin crowdin download sources -c crowdin/config.yml
DOCKER_USER=1000:1000 docker compose run --rm app-dev python manage.py makemessages -a --keep-pot
> make -n frontend-i18n-generate
DOCKER_USER=1000:1000 docker compose run --rm crowdin crowdin download sources -c crowdin/config.yml
cd ./src/frontend && …
```

🐛(i18n) fix `i18n-generate` make command

---

src/backend/mailbox_oauth2/validators.py

The PKCE is not available for Proconnect, security is made otherwise.

🐛(oauth2) disable PKCE for Proconnect

---

CHANGELOG.md
src/frontend/apps/desk/src/features/mail-domains/domains/api/useMailDomain.tsx
src/frontend/apps/desk/src/features/teams/team-management/api/useTeam.tsx

When the API returns a 404, the API is called again twice (three calls), this make the 404 display quite long and calling the API for nothing.
The solution here is a patch, I didn't find the root cause of that.

🐛(frontend) catch 404 for team/maildomain display

---

CHANGELOG.md
src/backend/core/apps.py
src/backend/core/tests/test_management_command_tasks.py
src/backend/core/utils/io.py
src/backend/people/settings.py

This allows to run management commands from a celery task.
Task should be referenced in the `MANAGEMENT_COMMAND_AS_TASK` setting.

🧑‍💻(tasks) run management commands

---

src/backend/core/api/client/viewsets.py
src/backend/core/tests/test_api_stats.py

Stats are currently counting all domains, including users tests. Counting enabled domains is more relevant to reflect actual use.

🧐(stats) restrict domains count to active domains

---

CHANGELOG.md
src/frontend/apps/desk/src/features/mail-domains/domains/api/useMailDomains.tsx
src/frontend/apps/desk/src/features/teams/team-management/api/useTeams.tsx
src/frontend/apps/e2e/__tests__/app-desk/mail-domain.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/mail-domains-add.spec.ts
src/frontend/apps/e2e/__tests__/app-desk/teams-create.spec.ts

Unblock #818 at least partially; improve functionality for end users; improve E2E tests.
Bug initially noticed by @elvoisin during #818 - when a nonsense value is substituted for the slug in a URL such as `/teams/rocket`, we intercept the error state and redirect to a 404 page. However, this only occurs after 4 calls are made to the underlying API (`/api/v1.0/teams` for instance) with increasingly long delays between calls. As a result, the E2E tests could only pass with an awkwardly long timeout inserted. For some reason (which I've not fully investigated), our rework of the UI was apparently making things even worse.
This turns out to have been a result of TanStack's "[aggressive but sane defaults](https://tanstack.com/query/v4/docs/framework/react/guides/important-defaults)", and …

🐛(front) disable retries in useQuery and useInfiniteQuery

---

docker-compose.yml

Make CI shorter and more reliable.
Remove `dimail` as a dependency of `app-dev` in `docker-compose`. The Gitlab instance hosting dimail images has become unstable resulting in excessive CI failures, and we don't actually depend on dimail for CI.

➖(dimail) remove ci-time dependency on dimail to improve CI times

---

docker-compose.yml

Over eager merge: we thought the impact on CI time indicated success… but was apparently just a fluke.
Reverts suitenumerique/people#842

Revert "➖(dimail) remove ci-time dependency on dimail to improve CI times"

---

env.d/development/france.dist
src/backend/people/settings.py
src/backend/plugins/organizations.py
src/backend/plugins/tests/organizations/test_commune_creation.py
src/frontend/apps/e2e/__tests__/app-desk/domain-provisioning.spec.ts

Ease management of subdomains created for testing purposes.
Currently domains for communes created during testing share the same destination (collectivite.fr) as the ones created during production.
Add a configuration setting tied to an env var, so we can have a separate zone for staging/preprod.
This way it's easier to tell which subdomains are for testing and can be deleted without user impact.
Default value is None to keep code generic.

🔧(dns) make target zone for communes domains configurable

---

CHANGELOG.md
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_create.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/utils/dimail.py

Remove duplicate sentry log and fix failure if response content has an unexpected format

🐛(dimail) enhance sentry log for dimail error

---

CHANGELOG.md
src/frontend/apps/desk/src/features/mail-domains/domains/components/MailDomainView.tsx

In use we realize that it is also necessary to be able to re-run dimail check on domain failed

✨(domains) allow to re-run check on failed domain

---

CHANGELOG.md
src/backend/core/tests/test_password_validators.py
src/backend/mailbox_manager/tests/test_password_validators.py
src/backend/people/settings.py
src/backend/pyproject.toml

This enabled various password validators to enforce password complexity.
Add password validators, but only for "production" environments.
Note, we may remove some of the default Django validators (except the `UserAttributeSimilarityValidator`), but I guess it's ok like this.

🔒️(passwords) add validators for production

---

src/backend/conftest.py
src/backend/core/tests/team_accesses/test_api_team_accesses_delete.py
src/backend/core/tests/test_models_team_accesses.py

The backend tests must not try to call the real world.
Prevents HTTP requests from being made during tests.
This is useful for tests that do not require actual HTTP requests
and helps to avoid network-related issues.
Credits: https://blog.jerrycodes.com/no-http-requests/

✅(pytest) fail on tests external calls

---

CHANGELOG.md
src/helm/desk/Chart.yaml
src/helm/desk/README.md
src/helm/desk/templates/backend_job_createsuperuser.yaml
src/helm/desk/values.yaml

This provides the way to disable the admin user creation at each deployment. In production we don't want to persist a generic admin user: it should be created once, at first deployment then replaced by nominative accounts.

🧱(helm) disable `createsuperuser` job by setting

---

src/backend/core/api/client/viewsets.py
src/backend/core/tests/test_api_stats.py

Public statistics on domains was modified to count only enabled domains. Modify stat name to reflect change.
Description...

🐛(stats) rename stat for clarity

---

env.d/development/common.e2e.dist
env.d/development/france.dist
src/backend/core/management/commands/list_plugins.py
src/backend/core/plugins/base.py
src/backend/core/plugins/registry.py
src/backend/plugins/la_suite/apps.py

This allows to use the application name, instead of the full path to the application configuration in the INSTALLED_PLUGINS setting.
Use a mix in for the application configuration.

🐛(plugin) allow simple application name

---

CHANGELOG.md
docker/auth/realm.json
src/backend/core/api/client/viewsets.py
src/backend/core/tests/users/test_api_users_list.py
src/backend/demo/management/commands/create_demo.py

This is a quick fix to a security issue. Previously, any user could list all users. Now /users/ endpoint only lists users from same organization.
We might improve this filter later but a quick fix would be good.
Description...

🔒️(users) restrict listable users to same organization

---

.github/workflows/release-helmchart.yml

We had an issue with the automatic helm chart releaser so we decide to trigger the job on every merge.

🐛(ci) remove path to trigger relaese helm chart

---

src/backend/mailbox_manager/admin.py

So far, "Synchronise from dimail" only import missing mailboxes from dimail, so this label needs to be more explicit.

💄(domain) enhance admin action label to import mailboxes

---

renovate.json

Dimail-api is currently outside of renovate' scope, which resulted in us having to check and update dimail's image manually or, if failing to, discovering new behaviors by chance or by errors in production. This should fix it.
Description...

🔧(renovate) add dimail-api to renovate scope

---

src/backend/pyproject.toml

This fixes the userinfo OIDC endpoint format autodetection.
Bump `django-lasuite` to version 0.0.7

⬆️(django-lasuite) bump version to v0.0.7

---

CHANGELOG.md
Makefile
docs/interoperability/dimail.md
src/backend/mailbox_manager/api/client/serializers.py
src/backend/mailbox_manager/signals.py
src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_create.py
src/backend/mailbox_manager/tests/api/mail_domain_accesses/test_api_mail_domain_accesses_create.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/tests/models/test_invitations.py
src/backend/mailbox_manager/utils/dimail.py

In this PR, we change the way people interact with dimail. We stop duplicating our users+permissions info to dimail. People with stop impersonating users in dimail and will create mailboxes using its own credentials (domain creation was already on its own credentials, nothing changes here).
We didn't remove `create_user` and `create_allows` methods in dimail client, because we need them to setup dimail database on local environments.
Description...

🛂(dimail) request as people

---

CHANGELOG.md
src/backend/people/settings.py

This should provide "cron" monitoring in Sentry.
See https://sentry.incubateur.net/organizations/betagouv/crons/

🔧(sentry) add Celery beat task integration

---

CHANGELOG.md
src/backend/mailbox_oauth2/tests/test_views.py
src/backend/people/settings.py

The `BrowsableAPIRenderer` generates a form to test POST/PUT/... actions and fill the FK fields with unfiltered data. 
https://github.com/user-attachments/assets/da8f7e52-cd26-403d-8d68-08a87b7e43ca
This issue has been spoted on visio and fixed https://github.com/suitenumerique/meet/pull/508

🔒️(drf) disable browsable HTML API renderer

---

CHANGELOG.md
docker-compose.yml
src/backend/mailbox_manager/api/client/viewsets.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_reset_password.py
src/backend/mailbox_manager/utils/dimail.py
src/mail/mjml/reset_password.mjml

We want domain admins and owners to be able to reset the password for a given mailbox on their domain. New password is randomly generated by dimail and sent to mailbox's secondary email.
Description...

✨(dimail) allow to reset the mailbox password

---

src/backend/mailbox_manager/admin.py
src/backend/mailbox_manager/tests/test_admin_actions.py
src/backend/mailbox_manager/tests/test_utils_dimail_client.py
src/backend/mailbox_manager/utils/dimail.py

Adds an admin action to send pending mailboxes on an active domain.
This is for debug purposes when mailbox creation failed in dimail and we end up with pending mailboxes.
Description...

✨(admin) send pending mailboxes from admin

---

Makefile
src/frontend/package.json

Some frontend lint can be fixed automatically, it should be easier for dev.
Add a Makefile command to easily run the automatic fixup for frontend files.

🧑‍💻(frontend) add makefile `lint --fix`

---

src/backend/mailbox_manager/api/client/viewsets.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_reset_password.py
src/backend/mailbox_manager/tests/fixtures/dimail.py
src/backend/mailbox_manager/tests/test_utils_dimail_client.py
src/backend/mailbox_manager/utils/dimail.py
src/frontend/apps/desk/src/features/mail-domains/mailboxes/api/useUpdateMailboxStatus.tsx
src/frontend/apps/desk/src/features/mail-domains/mailboxes/components/panel/PanelActions.tsx

Domain admins and owners can now send requests to reset password for any mailbox properly configured on domains they manage.
I'm thinking about deactivating the "cannot reset password" button entirely when mailbox is disabled.
Description...
Confirmation toasts
- As discussed in review, we'll wait for feature to be more mature to write e2e tests

✨(frontend) add button to reset password

---

.gitattributes
CHANGELOG.md

Windows users are by default using CRLF line endings, which can cause issues with some tools and
environments. This commit sets the `.gitattributes` file to enforce LF line endings for all text
files in the repository.
Based on the same commit on docs : https://github.com/suitenumerique/docs/commit/fbb27990508fee7184a32675c226799c7a8a7b11
See above

 🔧(git) set LF line endings for all text files

---

src/backend/mailbox_manager/signals.py
src/backend/mailbox_manager/tests/api/invitations/test_api_domain_invitations_create.py
src/backend/mailbox_manager/tests/models/test_invitations.py

reduce logs and add tests around domain invitations
Description...

🐛(domains) improve logs around domain invitations

---

src/backend/core/tests/utils/test_webhooks_matrix_client.py
src/backend/core/utils/matrix.py

Our Tchap webhook contains no secret (as we use the provided dedicated access token).
This lead to an error upon trying to join rooms.
Description...

🐛(webhook) fix error raised when no secret

---

src/backend/core/tests/team_accesses/test_api_team_accesses_create.py
src/backend/core/utils/matrix.py

Matrix webhook calls were unverified and caused a security warning. Setting option "verify" to "True" on related calls should help.
! In my local environment, I still receive a 405 Not allowed error from Nginx.
This is the response I get from my calls to https://tchap.gouv.fr
Description...
- [] item 1...
- [] item 2...

🐛(webhooks) fix InsecureRequestWarning from webhook calls

---

src/backend/core/tests/utils/test_webhooks_matrix_client.py
src/backend/core/utils/matrix.py

we want to use Tchap integration server for our own preprod but this server doesn't follow the same url naming convention as the other Tchap instances, so it requires a special treatment. This quick fix should do it.

🐛(webhooks) fix special case for tchap integration

---

src/backend/mailbox_manager/admin.py

removed read_only on "local_part" and "domain" which prevented admin user from creating mailboxes from admin
Description...
- [] item 1...
- [] item 2...

🐛(admin) fix read_only preventing mailbox creation in admin

---

src/backend/pyproject.toml

This allows to accept JWE from new Proconnect introspection endpoint.

⬆️(django-lasuite) bump to version 0.0.11

---

src/backend/people/settings.py

set default `SENTRY_DSN` value to None to avoid all outside deployments sending infos to our sentry instance.

🐛(config) remove default sentry_dsn

---

CHANGELOG.md
src/backend/people/settings.py
src/helm/env.d/dev-keycloak/values.desk.yaml.gotmpl
src/helm/env.d/dev/values.desk.yaml.gotmpl

Other "La Suite" projects don't have the "DJANGO_" prefix, so we align this project with others.

💥(sentry) remove `DJANGO_` before Sentry DSN env variable

---

.github/workflows/people.yml

`git whatchanged` got nominated for removal and now requires an additional option to run, to confirm that we still use it.
@qbey should I send a quick mail or do you want to do it ?

💚(ci) fix changelog CI job

---

CHANGELOG.md
src/backend/mailbox_manager/api/client/serializers.py
src/backend/mailbox_manager/api/client/viewsets.py
src/backend/mailbox_manager/api/permissions.py
src/backend/mailbox_manager/models.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_patch.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_put.py
src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_retrieve.py

Allow update of mailboxes. Secondary email, first and last names can be updated but not
domain or local_part. Also introduces the notion of "self" in permissions, allowing for a
domain viewer to update their own mailbox.
Description...

✨(api) update mailboxes
