suitenumerique/people

- .github/workflows/people.yml
pylint and ruff are now reporting linting issues
> 👷(ci) fix python linting

- .github/workflows/people.yml
check-changelog should only runs on PR
> 👷(ci) fix ci issue with changelog

- .github/workflows/people.yml
- src/frontend/app/desk/.eslintrc.js
- src/frontend/app/desk/jest.config.ts
- src/frontend/app/desk/package.json
- src/frontend/app/desk/src/app/__tests__/page.test.tsx
- src/frontend/app/desk/yarn.lock
Jest is a JavaScript Testing Framework, usefull to test React components and to do unit testing.
> ✅(app-desk) install jest

- src/backend/core/api/serializers.py
- src/backend/core/api/viewsets.py
- src/backend/core/tests/test_api_users.py
- src/backend/core/tests/test_throttle.py
- src/backend/people/settings.py
We want to create the api endpoint to later allow user search by email. 
Creation of the api endpoint /users/
> ✨(api) search users by email

- renovate.json
Explicit Renovate bot status between two PR.
Enable renovate bot to open an issue with a dependency dashboard.
> 🔧(project) enable renovate dependency dashboard

- .sops.yaml
Identified and resolved minor code formatting issues.
Updates:
* Add a newline at the end of the file
* Capitalize first names and last names of all users.
> 🎨(project) fixed minor code formatting issues in .sops.yaml

- Makefile
- README.md
- gitlint/gitlint_emoji.py
- src/backend/core/models.py
- src/backend/core/tests/test_models_oidc_user_getter.py
- src/backend/demo/management/commands/createsuperuser.py
- src/backend/people/settings.py
> ✏️(project) fix minor typos

- src/backend/core/admin.py
- src/backend/core/api/serializers.py
- src/backend/core/factories.py
- src/backend/core/migrations/0001_initial.py
- src/backend/core/models.py
- src/backend/core/tests/test_models_invitations.py
- src/backend/people/settings.py
Create `Invitation` model, factory and related tests, in order to facilitate incoming developments surrounding user invitation.
We chose to create a separate dedicated model for separation of concerns, see https://github.com/numerique-gouv/people/issues/25
> 🗃️(model) create invitation model

- src/backend/people/settings.py
- src/backend/pyproject.toml
Prepare staging deployment
Set-up Redis cache.
> 🔧(backend) configure RedisCache in production settings

- src/backend/people/settings.py
- src/helm/env.d/dev/secrets.enc.yaml
- src/helm/env.d/dev/values.desk.yaml.gotmpl
- src/helm/env.d/staging/secrets.enc.yaml
- src/helm/env.d/staging/values.desk.yaml.gotmpl
Discussed with @rouja, I fixed few Django configurations in staging.
> Fix email sending in staging

- src/frontend/apps/desk/.gitignore
- src/frontend/apps/desk/.prettierignore
- src/frontend/apps/desk/next-env.d.ts
- src/frontend/apps/desk/package.json
- src/frontend/apps/desk/src/api/__tests__/fetchApi.test.tsx
- src/frontend/apps/desk/src/features/members/__tests__/MemberAction.test.tsx
- src/frontend/apps/e2e/__tests__/app-desk/common.ts
- src/frontend/apps/e2e/__tests__/app-desk/member-create.spec.ts
> ✅(e2e) fix job flakinness

- src/backend/mailbox_manager/api/serializers.py
- src/backend/mailbox_manager/api/viewsets.py
- src/backend/mailbox_manager/tests/test_api_mailboxes_create.py
- src/backend/mailbox_manager/tests/test_api_mailboxes_list.py
- src/backend/people/api_urls.py
> ✨(api) allow to list and create Mailboxes

- src/backend/mailbox_manager/admin.py
- src/backend/mailbox_manager/models.py
Register MailDomain, MailDomainAccess and Mailbox to django admin.
To ease things up for dev and test purposes.
Description...
- [] item 1...
- [] item 2...
> 🧑‍💻(admin) register mailbox-related models to django admin

- src/helm/env.d/staging/secrets.enc.yaml
- src/helm/env.d/staging/values.desk.yaml.gotmpl
- src/helm/extra/templates/secrets.yaml
- src/helm/helmfile.yaml
Avoid secrets to be visible from running deployments
> 💚(ci) improve secrets for k8s deployment

- src/frontend/apps/desk/jest.setup.ts
- src/frontend/apps/desk/src/components/Box.tsx
- src/frontend/apps/desk/src/components/TextErrors.tsx
- src/frontend/apps/desk/src/components/__tests__/Box.spec.tsx
- src/frontend/apps/desk/src/features/addMembers/components/ModalAddMembers.tsx
- src/frontend/apps/desk/src/features/header/Header.tsx
- src/frontend/apps/desk/src/features/mails/components/MailContent.tsx
- src/frontend/apps/desk/src/features/members/components/MemberGrid.tsx
- src/frontend/apps/desk/src/features/members/components/ModalDelete.tsx
- src/frontend/apps/desk/src/features/members/components/ModalRole.tsx
- src/frontend/apps/desk/src/features/menu/Menu.tsx
- src/frontend/apps/desk/src/features/menu/MenuItems.tsx
- src/frontend/apps/desk/src/features/menu/Tooltip.tsx
- src/frontend/apps/desk/src/features/teams/components/CardCreateTeam.tsx
- src/frontend/apps/desk/src/features/teams/components/ModalRemoveTeam.tsx
- src/frontend/apps/desk/src/features/teams/components/ModalUpdateTeam.tsx
- src/frontend/apps/desk/src/features/teams/components/Panel/Panel.tsx
- src/frontend/apps/desk/src/features/teams/components/Panel/TeamItem.tsx
- src/frontend/apps/desk/src/features/teams/components/Panel/TeamList.tsx
- src/frontend/apps/desk/src/features/teams/components/TeamInfo.tsx
- src/frontend/apps/desk/src/pages/404.tsx
- src/frontend/apps/desk/src/pages/teams/create.tsx
- src/frontend/apps/desk/src/utils/styleBuilder.ts
Add spacing props (margin / padding) to Box component and its inheritances.
It proposes the autocompletion.
It is bind with the Cunningham spacing system.
> 🎨Box spacing

- src/backend/core/authentication/backends.py
- src/backend/core/authentication/urls.py
- src/backend/core/authentication/views.py
- src/backend/core/tests/authentication/test_backends.py
- src/backend/core/tests/authentication/test_urls.py
- src/backend/core/tests/authentication/test_views.py
- src/backend/people/api_urls.py
- src/backend/people/settings.py
- src/frontend/apps/desk/src/api/__tests__/fetchApi.test.tsx
- src/frontend/apps/desk/src/core/auth/api/index.ts
- src/frontend/apps/desk/src/core/auth/api/logout.ts
- src/frontend/apps/desk/src/core/auth/useAuthStore.tsx
- src/frontend/apps/e2e/__tests__/app-desk/header.spec.ts
- src/helm/env.d/dev/values.desk.yaml.gotmpl
- src/helm/env.d/staging/values.desk.yaml.gotmpl
End OIDC provider session while logging out.
It closes #149
> Logout backend

- Dockerfile
- Makefile
- bin/Tiltfile
- bin/start-kind.sh
- src/helm/desk/templates/backend_deployment.yaml
- src/helm/desk/templates/backend_job.yaml
- src/helm/desk/templates/backend_svc.yaml
- src/helm/desk/templates/frontend_deployment.yaml
- src/helm/desk/templates/frontend_svc.yaml
- src/helm/desk/templates/ingress.yaml
- src/helm/desk/templates/ingress_admin.yaml
- src/helm/desk/templates/secrets.yaml
- src/helm/env.d/dev/secrets.enc.yaml
- src/helm/env.d/dev/values.desk.yaml.gotmpl
- src/helm/helmfile.yaml
Tilt makes running your cluster k8s in local, it is a great tool to dev or debug your cluster before deploying.
In order to have Tilt working you must have this stack on your machine:
- kubectl
- helm
- helmfile
- plugin helm-diff
- plugin helm-secrets
- kind
- docker
```sh
make start-kind
kubectl get po -A
make tilt-up
```
Tilt interface: 
http://localhost:10350/
When all is green:
https://desk.127.0.0.1.nip.io
> Configure Tilt

- .github/workflows/docker-hub.yml
- .github/workflows/people.yml
- .gitmodules
- src/helm/env.d/staging/secrets.enc.yaml
- src/helm/helmfile.yaml
- remove deplucate declaration
- simplify helmfile
- use symlink
> 💚(ci) improve submodule usage

- bin/Tiltfile
- src/helm/desk/templates/backend_job_createsuperuser.yaml
- src/helm/env.d/dev/values.desk.yaml.gotmpl
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/staging/values.desk.yaml.gotmpl
- src/helm/extra/templates/secrets.yaml
We need a superuser in the Django application, to have access to the admin part.
This PR create a superuser on the pods.
> 👷(helm) command createsuperuser

- src/helm/env.d/dev/values.desk.yaml.gotmpl
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
- src/helm/env.d/staging/values.desk.yaml.gotmpl
The createsuperuser command changes recently.
We update the command to reflect the changes.
> 🐛(helm) fix createsuperuser command

- src/backend/core/admin.py
> ✨(models) add TeamAccess models on admin view

- src/backend/mailbox_manager/api/permissions.py
- src/backend/mailbox_manager/api/serializers.py
- src/backend/mailbox_manager/api/viewsets.py
- src/backend/mailbox_manager/models.py
- src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_retrieve.py
- src/backend/mailbox_manager/tests/test_api_mailboxes_create.py
- src/backend/mailbox_manager/tests/test_api_mailboxes_list.py
- src/backend/mailbox_manager/tests/test_models_maildomain.py
Manage create and list permissions for all roles.
> ✨ (mail) manage mailboxes permissions

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
🎉! For changelog, see changelog.md
> 🔖(major) major release to 1.0.0

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
- src/mail/package.json
- src/tsclient/package.json
Release missing UI features to add existing mail domains.
- upgrade semver for all package.json, env.d files, and pyproject.toml
- update CHANGELOG.md
> 🔖(patch) patch release to 1.0.1

- CHANGELOG.md
- src/backend/mailbox_manager/factories.py
- src/backend/mailbox_manager/models.py
- src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
- src/backend/mailbox_manager/tests/test_models_mailboxes.py
- src/backend/mailbox_manager/utils/dimail.py
- src/backend/people/settings.py
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
- src/helm/env.d/staging/values.desk.yaml.gotmpl
Latest dimail modification lead to a bug in our app, preventing mailbox creation from working properly.
> 👽️(mailboxes) fix mailbox creation after dimail api improvement

- src/helm/desk/templates/secrets.yaml
- src/helm/env.d/staging/values.desk.yaml.gotmpl
Configure resource server in staging
Refer to the merged #308 PR which describes what's a Resource Server.
These client id / secret are generated manually by Agent Connect Ops.
If at any point you need to update them, please contact kevin masseix
> Configure resource server in staging

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
Update all version files and changelog for release patch.
> 🔖(patch) release version 1.0.2

- src/backend/mailbox_manager/utils/dimail.py
simple refacto to catch all 500 errors, including when asking for a new token.
By reporting all dimail 500 the same way, it's easier to make sense of monitoring in Sentry.
Description...
- [] item 1...
- [] item 2...
> ♻️(dimail) refacto to better handle 500 errors from dimail

- Makefile
- scripts/release.py
- scripts/utils.py
Change versions, update changelog and create branch and commit to submit release informations.
Give following instructions to do after.
> ✨(release) add python script to prepare release

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
This is our first automated release ! \o/
> 🔖(minor) release version 1.1.0

- CHANGELOG.md
- src/backend/mailbox_manager/api/serializers.py
- src/backend/mailbox_manager/api/viewsets.py
- src/backend/mailbox_manager/tests/api/mail_domain_accesses/test_api_mail_domain_accesses_list.py
- src/backend/mailbox_manager/tests/api/mail_domain_accesses/test_api_mail_domain_accesses_retrieve.py
Description...
Description...
- [] item 1...
- [] item 2...
> ✨(backend) list all accesses for a domain API

- Makefile
- src/backend/mailbox_manager/management/commands/setup_dimail_db.py
We recently added a dimail-api container to ease dimail-related development. 
this commit adds a script and 'make' command to populate dimail database
with basic objects: an admin account, a regie account, a domain
and an owner for this domain.
> ✨(dimail) populate dimail local database for dev use

- CHANGELOG.md
- src/backend/mailbox_manager/api/serializers.py
- src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
- src/backend/mailbox_manager/utils/dimail.py
- src/backend/people/settings.py
- src/helm/env.d/dev/values.desk.yaml.gotmpl
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
- src/helm/env.d/staging/values.desk.yaml.gotmpl
- src/mail/mjml/new_mailbox.mjml
send mailbox information upon creating a new mailbox
Description...
> ✨(mailbox) send new mailbox confirmation email

- .github/workflows/helmfile-linter.yml
- CHANGELOG.md
- src/helm/desk/templates/backend_job.yaml
- src/helm/desk/templates/backend_job_createsuperuser.yaml
Add a linter to avoid to merge config that breaks argocd sync
> ✨(ci) add helmfile linter

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
> 🔖(minor) release version 1.2.0

- src/helm/env.d/production/values.desk.yaml.gotmpl
wrong value in dimail api url was causing prod to not work
Description...
- [] item 1...
- [] item 2...
> 🐛(helm) fix dimail api url

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
Description...
- [] item 1...
- [] item 2...
> 🔖(patch) release version 1.2.1

- src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
- src/backend/mailbox_manager/utils/dimail.py
add status code in case of unexpected error
Description...
- [] item 1...
- [] item 2...
> 🐛(dimail) add status code in case of unexpected error

- src/backend/people/settings.py
we reduce trace to reduce spamming on sentry
Description...
Description...
- [] item 1...
- [] item 2...
> 🔧(sentry) reduce trace

- README.md
- docs/interoperability/dimail.md
update docs on dimail to describe interoperability between la régie and dimail
Description...
> 📝(dimai) update docs on dimail

- CHANGELOG.md
- src/backend/mailbox_manager/admin.py
Allow to manage mail domain roles on mail domain admin interface
Fixes #440
Description...
Description...
- [] item 1...
- [] item 2...
> ✨(backend) manage roles on domain admin view

- CHANGELOG.md
Some unreleased declarations was declared in a wrong place
> 📝(CHANGELOG) fix some modifications declaration

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
Description...
- [] item 1...
- [] item 2...
> 🔖(minor) release version 1.3.0

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
Manually fix frontend image version (to be added in release script !)
Description...
- [] item 1...
- [] item 2...
> 🔖(patch) release version 1.3.1

- CHANGELOG.md
- scripts/release.py
Use regex to replace version and add missing frontend update version.
> 🐛(script) improve and fix release script

- CHANGELOG.md
One of unreleased modification declaration was
declared in a wrong place
> 📝(CHANGELOG) fix modification declaration

- CHANGELOG.md
- src/frontend/apps/desk/src/features/mail-domains/domains/components/MailDomainsLayout.tsx
The content is not scrollable. We add an auto overflow to solve this problem
> 🚑️(frontend) fix MailDomainsLayout

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
> 🔖(patch) release version 1.4.1

- .github/workflows/people.yml
- CHANGELOG.md
e2e tests take too long to run. We can easily reduce this time by adding shards
> 👷(ci) add sharding e2e tests

- scripts/release.py
Some instructions are missing to explain manual steps
> ✏️(scripts) add some details for manual steps

- CHANGELOG.md
- src/backend/core/admin.py
Allow to manage contact on admin interface
> ✨(teams) register contacts on admin views

- CHANGELOG.md
- src/backend/core/api/viewsets.py
- src/backend/core/tests/test_api_users.py
- src/backend/demo/management/commands/create_demo.py
- src/backend/demo/tests/test_commands_create_demo.py
- src/frontend/apps/e2e/__tests__/app-desk/member-delete.spec.ts
- src/frontend/apps/e2e/playwright.config.ts
This feature is not necessary for our users now
and we got some strange results so we decided
to remove this feature.
Fixes #477
> 🔥(teams) remove search users by trigram

- Makefile
- src/backend/mailbox_manager/management/commands/setup_dimail_db.py
- src/backend/mailbox_manager/tests/test_command_dimail_setup_db.py
Test (and slightly improve) dimail setup command, which populate db on local dimail container
Description...
- [] item 1...
- [] item 2...
> ✅(tests) test dimail setup command

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
> 🔖(minor) release version 1.5.0

- CHANGELOG.md
- src/backend/core/api/viewsets.py
- src/backend/core/tests/test_api_contacts.py
Remove trigram search for team access and contact
> 🔥(teams) remove all search by trigram

- docker-compose.yml
Pin dimail-api version to fix main branch temporarily…
> Pin dimail-api version to fix main branch

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
> 🔖(minor) release version 1.6.0

- CHANGELOG.md
- src/backend/mailbox_manager/admin.py
- src/backend/mailbox_manager/migrations/0015_change_mailboxes_status_to_enabled.py
All mailboxes created so far should be in active status
> 🩹(mailbox) fix status of current mailboxes

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
> 🔖(patch) release version 1.6.1

- scripts/release.py
Remove useless option to create tag
> 📝(scripts) improve command to do to release

- CHANGELOG.md
- docker-compose.yml
- src/backend/locale/fr_FR/LC_MESSAGES/django.po
- src/backend/mailbox_manager/admin.py
- src/backend/mailbox_manager/api/client/serializers.py
- src/backend/mailbox_manager/api/client/viewsets.py
- src/backend/mailbox_manager/models.py
- src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_create.py
- src/backend/mailbox_manager/tests/api/mailboxes/test_api_mailboxes_disable.py
- src/backend/mailbox_manager/tests/test_models_mailboxes.py
- src/backend/mailbox_manager/tests/test_utils_dimail_client.py
- src/backend/mailbox_manager/utils/dimail.py
> Disable mailbox

- docs/organizations.md
- docs/serviceProviders.md
This introduces a very light documentation about
the newly introduced models.
> 📝(docs) light doc about org & SP

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
> 🔖(minor) release version 1.7.0

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
> 🔖(patch) release version 1.7.1

- src/helm/env.d/staging/values.desk.yaml.gotmpl
This fixes validator for the Organization
registration ID for staging (to enforce SIRET format).
> 🔧(helm) fix siret validator for staging

- docs/models.md
This update the documentation to reflect latest
changes:
- drop `Identity`
- `Contact` model updates
> 📝(contacts) update documentation

- src/backend/mailbox_manager/management/commands/setup_dimail_db.py
> 🐛(dimail) fix dimail setup command

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
> 🔖(minor) release version 1.8.0

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
Description...
Description...
- [] item 1...
- [] item 2...
> 🔖(minor) release version 1.9.0

- docker-compose.yml
- src/backend/mailbox_manager/api/client/serializers.py
Upgrade dimail to v0.1.1 to fit version deployed in dimail dev.
⚠️ Check v0.1.1 is in dimail prod before pushing to prod on our end ?
> ⬆️(dimail) upgrade dimail to v0.1.1

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
- src/helm/env.d/preprod/values.desk.yaml.gotmpl
- src/helm/env.d/production/values.desk.yaml.gotmpl
Description...
Description...
- [] item 1...
- [] item 2...
> 🔖(patch) release version 1.9.1

- scripts/release.py
Do not forget to check docker image of frontend.
> 📝(scripts) add missing release instructions

- src/backend/mailbox_manager/admin.py
Allow to filter domain by status
Description...
Description...
- [] item 1...
- [] item 2...
> 🧑‍💻(admin) add filter for domain

- CHANGELOG.md
- src/frontend/apps/e2e/__tests__/app-desk/member-delete.spec.ts
Small hack to fix clicking on member action button.
Action button of the third member in the list could not
be clickable every time.
The member list table needs and will be improved soon.
> fix flaky e2e test

- CHANGELOG.md
- src/backend/core/tests/team_accesses/test_api_team_accesses_list.py
Faker sometimes creates users whose name starts with "Ms." or "Mr." The implemented test code computed the order without handling these cases and failed.
> 🐛(backend) fix flaky test with team access #646

- Makefile
- bin/Tiltfile
- docs/local_development_kube.md
- src/helm/dimail/Chart.yaml
- src/helm/dimail/templates/deployment.yaml
- src/helm/dimail/templates/ingress.yaml
- src/helm/dimail/templates/service.yaml
- src/helm/dimail/values.yaml
- src/helm/env.d/dev/values.desk.yaml.gotmpl
- src/helm/helmfile.yaml
For local developments we add a dimail in the kubernetes stack
Description...
> 🧑‍💻(tilt) add dimail for local developments

- bin/install-external-secrets.sh
My previous PR was merged to quickly, I forgot to add the file to create the secret for Tilt.
> 🐛(tilt) add missing file after previous commit

- CHANGELOG.md
- src/backend/core/api/client/viewsets.py
- src/backend/core/tests/test_api_stats.py
- src/backend/people/api_urls.py
create stats endpoint to expose public metrics
Description...
> ✨(api) create stats endpoint

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
Update all version files and changelog for minor release. heml/env.d/preprod and prod directories are now on another repo.
Description...
- [] item 1...
- [] item 2...
> 🔖(minor) release version 1.10.0

- CHANGELOG.md
- scripts/release.py
Description...
Description...
- [] item 1...
- [] item 2...
> Mise à jour du script de release

- CHANGELOG.md
- src/backend/core/api/client/viewsets.py
- src/backend/core/tests/test_api_stats.py
Add cache to display stats for anonymous
and improve some code.
> ⚡️(api) add missing cache for stats endpoint

- CHANGELOG.md
- src/backend/pyproject.toml
> 🔖(patch) release version 1.10.1

- .github/workflows/deploy.yml
- .github/workflows/docker-hub.yml
- CHANGELOG.md
- src/backend/plugins/organizations.py
- src/backend/plugins/tests/organizations/test_name_from_siret_organization_plugin.py
For some SIRET, there are no "liste_enseignes" (null), in such cases we fallback on the global "company" name.
Fixes https://sentry.incubateur.net/organizations/betagouv/issues/146062/
> 🚑️(plugins) fix name from SIRET specific case

- src/helm/env.d/dev/values.desk.yaml.gotmpl
- src/helm/helmfile.yaml
- src/helm/mailcatcher/Chart.yaml
- src/helm/mailcatcher/templates/deployment.yaml
- src/helm/mailcatcher/templates/ingress.yaml
- src/helm/mailcatcher/templates/service.yaml
- src/helm/mailcatcher/values.yaml
This allows to start a mailcatcher for local developments.
> 🧑‍💻(tilt) add mailcatcher to the stack

- src/backend/core/models.py
- src/backend/core/tests/test_models_invitations.py
- src/backend/locale/fr_FR/LC_MESSAGES/django.po
- src/mail/mjml/invitation.mjml
Regenerate translations, translate some and
replace "Desk" and "Régie" to "La Régie".
C'est probablement le moment de passer le nom dans un settings ? @qbey
> 🌐(backend) add missing translations

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
> 🔖(minor) release version 1.11.0

- .github/ISSUE_TEMPLATE/Support_question.md
- CHANGELOG.md
- src/backend/core/authentication/backends.py
- src/backend/pyproject.toml
- src/frontend/apps/desk/src/components/Modal.tsx
- src/frontend/apps/desk/src/features/language/LanguagePicker.tsx
- src/mail/package.json
- src/tsclient/package.json
github repo moved from numerique-gouv to suitenumerique org
update all mentions to github repo
> 🚚(github) update all mentions to github repo

- CHANGELOG.md
- src/backend/mailbox_manager/api/client/serializers.py
- src/backend/mailbox_manager/tests/api/mail_domain/test_api_mail_domains_create.py
- src/backend/mailbox_manager/utils/dimail.py
Fetch domain status from dimail just after domain creation.
Ça serait bien d'envisager prochainement d'implémenter une erreur custom pour dimail (cc @qbey )
> ✨(domains) check status after creation

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
> 🔖(minor) release version 1.12.0

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
> 🔖(patch) release version 1.12.1

- CHANGELOG.md
- src/helm/desk/Chart.yaml
- src/helm/desk/templates/ingress.yaml
The route was added but not declared in the ingress.
> 🧱(helm) add `resource-server` ingress path

- scripts/release.py
Add explicit links to current and deployment repositories and change commit message to bump preprod version on deployment repo.
> 🧑‍💻(scripts) improve release script

- CHANGELOG.md
- src/backend/mailbox_manager/utils/dimail.py
- src/frontend/apps/desk/src/features/mail-domains/domains/components/MailDomainView.tsx
fix https://github.com/suitenumerique/people/issues/750
> Improve check domain

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
> 🔖(minor) release version 1.13.0

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
> 🔖(patch) release version 1.13.1

- src/backend/core/api/permissions.py
- src/backend/core/api/resource_server/serializers.py
- src/backend/core/api/resource_server/viewsets.py
- src/backend/core/tests/resource_server_api/teams_invitations/__init__.py
- src/backend/core/tests/resource_server_api/teams_invitations/test_create.py
- src/backend/core/tests/resource_server_api/teams_invitations/test_delete.py
- src/backend/core/tests/resource_server_api/teams_invitations/test_list.py
- src/backend/core/tests/resource_server_api/teams_invitations/test_retrieve.py
- src/backend/people/resource_server_urls.py
This allows a service provider to add new members to a team.
> ✨(resource-server) add team invitation endpoint

- docker-compose.yml
Update crowdin for the best experience :D
> ⬆️(docker) bump crowdin version to 4.6.1

- CONTRIBUTING.md
Duplicate docs CONTRIBUTING.md and add part about
process to have a nice commit history.
> 📝(CONTRIBUTING) describe how to contribute on project

- CHANGELOG.md
- src/backend/mailbox_manager/utils/dimail.py
- src/backend/people/settings.py
In use a timeout of 30 seconds seems more appropriate
> ✨(api) define dimail timeout as a setting

- CHANGELOG.md
- Dockerfile
Bump nginx-unprivileged to the latest version
> ⬆️(nginx) bump nginx-unprivileged to 1.27

- .github/workflows/crowdin_upload.yml
- .github/workflows/dependencies.yml
- .github/workflows/people.yml
Update Crowdin translation everytime the main branch is updated.
> 👷(crowdin) upload main translations to crowdin

- src/mail/mjml/maildomain_invitation.mjml
- src/mail/mjml/team_invitation.mjml
Some explanations were forgotten.
Delete useless trans on 'La Régie'
> ✨(mail) add missing text and remove useless translations

- docs/i18n.md
Propose a way to check if every is ok before
upload on crowdin
> 📝(i18n) add details about translation process

- CHANGELOG.md
- src/frontend/apps/desk/src/features/mail-domains/domains/__tests__/MailDomainView.test.tsx
- src/frontend/apps/desk/src/features/mail-domains/domains/components/MailDomainView.tsx
Enhance DNS required actions and explanations
> ✨(domains) enhance required action modal content

- .github/workflows/crowdin_download.yml
- docs/release.md
Make the release process smooth and check for missing translations.
> 👷(release) improve process and checks

- docs/release.md
Update and fix doc
Description...
Description...
- [] item 1...
- [] item 2...
> 📝(release) fix documentation

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
> 🔖(minor) release version 1.14.0

- CHANGELOG.md
- src/backend/people/settings.py
- src/helm/desk/Chart.yaml
- src/helm/desk/templates/ingress.yaml
The route was added but not declared in the ingress.
> 🧱(helm) add la-suite ingress path

- CHANGELOG.md
- src/backend/locale/en_US/LC_MESSAGES/django.po
- src/backend/locale/fr_FR/LC_MESSAGES/django.po
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/desk/src/i18n/translations.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
> 🔖(minor) release version 1.15.0

- scripts/release.py
Add information about settings and helm chart to configure Add more details about translations PR autogenerated
> 📝(scripts) enhance release scripts instructions

- SECURITY.md
Add a basic security disclosure policy
Copy Docs policy nearly verbatim…
> 📝(security) add a basic security disclosure policy

- CHANGELOG.md
- src/backend/locale/en_US/LC_MESSAGES/django.po
- src/backend/locale/fr_FR/LC_MESSAGES/django.po
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
> 🔖(minor) release version 1.16.0

- CHANGELOG.md
Fixing changelog after having forgotten to update it in last release (1.16.0)
> 🔖(changelog) fix changelog

- Dockerfile
Trivy scan detects some issue on libxml2 for the frontend image. I'm not sure we need it...
Force an update on libxml2.
> 🔒️(docker) patch libxml to address CVE

- CHANGELOG.md
- src/backend/core/api/client/viewsets.py
- src/backend/core/tests/test_api_config.py
- src/backend/people/settings.py
- src/frontend/apps/desk/src/__tests__/pages.test.tsx
- src/frontend/apps/desk/src/core/config/types.ts
- src/frontend/apps/desk/src/pages/_app.tsx
- src/frontend/apps/e2e/__tests__/app-desk/config.spec.ts
add crisp chatbox to global layout
> 💻(frontend) add crisp script

- CHANGELOG.md
- src/backend/locale/en_US/LC_MESSAGES/django.po
- src/backend/locale/fr_FR/LC_MESSAGES/django.po
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/desk/src/i18n/translations.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
> 🔖(minor) release version 1.18.0

- CHANGELOG.md
- src/backend/pyproject.toml
- src/frontend/apps/desk/package.json
- src/frontend/apps/e2e/package.json
- src/frontend/package.json
- src/frontend/packages/eslint-config-people/package.json
- src/frontend/packages/i18n/package.json
> 🔖(patch) release version 1.18.2

- CHANGELOG.md
- src/frontend/apps/desk/src/features/mail-domains/mailboxes/components/panel/MailBoxesListView.tsx
- src/frontend/apps/desk/src/features/mail-domains/mailboxes/components/panel/PanelActions.tsx
- src/frontend/apps/desk/src/features/mail-domains/mailboxes/types.ts
can update your mailbox as viewer
> 🐛(fix) add enabled update your mailbox
